-- =============================================
-- Panini FIFA World Cup 2026 — Catálogo OFICIAL
-- Fuente: cartophilic-info-exch.blogspot.com / checklistinsider.com
-- 20 intro + 48 equipos × 20 láminas = 980 láminas reales
-- =============================================

TRUNCATE TABLE public.user_stickers;
TRUNCATE TABLE public.stickers RESTART IDENTITY CASCADE;

INSERT INTO public.stickers (section, number, name, type) VALUES

-- =============================================
-- INTRODUCCIÓN (1-20)
-- 00 + FWC1-FWC19
-- =============================================
('Introducción', 1,  'Logo Panini',                    'special'),
('Introducción', 2,  'Emblema Oficial 1/2',             'special'),
('Introducción', 3,  'Emblema Oficial 2/2',             'special'),
('Introducción', 4,  'Mascota Oficial',                 'special'),
('Introducción', 5,  'Eslogan Oficial',                 'special'),
('Introducción', 6,  'Balón Oficial',                   'special'),
('Introducción', 7,  'Canadá — Países y Ciudades Sede', 'special'),
('Introducción', 8,  'México — Países y Ciudades Sede', 'special'),
('Introducción', 9,  'USA — Países y Ciudades Sede',    'special'),
('Introducción', 10, 'Historia: Italia 1934',           'special'),
('Introducción', 11, 'Historia: Uruguay 1950',          'special'),
('Introducción', 12, 'Historia: Alemania Occ. 1954',    'special'),
('Introducción', 13, 'Historia: Brasil 1962',           'special'),
('Introducción', 14, 'Historia: Alemania Occ. 1974',    'special'),
('Introducción', 15, 'Historia: Argentina 1986',        'special'),
('Introducción', 16, 'Historia: Brasil 1994',           'special'),
('Introducción', 17, 'Historia: Brasil 2002',           'special'),
('Introducción', 18, 'Historia: Italia 2006',           'special'),
('Introducción', 19, 'Historia: Alemania 2014',         'special'),
('Introducción', 20, 'Historia: Argentina 2022',        'special'),

-- =============================================
-- ALGERIA — ALG (21-40)
-- =============================================
('Algeria', 21, 'Escudo Algeria',       'badge'),
('Algeria', 22, 'Alexis Guendouz',      'player'),
('Algeria', 23, 'Ramy Bensebaïni',      'player'),
('Algeria', 24, 'Youcef Atal',          'player'),
('Algeria', 25, 'Rayan Aït-Nouri',      'player'),
('Algeria', 26, 'Mohamed Amine Tougai', 'player'),
('Algeria', 27, 'Aïssa Mandi',          'player'),
('Algeria', 28, 'Ismail Bennacer',      'player'),
('Algeria', 29, 'Houssem Aquar',        'player'),
('Algeria', 30, 'Hicham Boudaoui',      'player'),
('Algeria', 31, 'Ramiz Zerrouki',       'player'),
('Algeria', 32, 'Nabil Bentalab',       'player'),
('Algeria', 33, 'Plantel Algeria',      'special'),
('Algeria', 34, 'Farès Chaïbi',         'player'),
('Algeria', 35, 'Riyad Mahrez',         'player'),
('Algeria', 36, 'Said Benrahma',        'player'),
('Algeria', 37, 'Anis Hadj Moussa',     'player'),
('Algeria', 38, 'Amine Gouiri',         'player'),
('Algeria', 39, 'Baghdad Bounedjah',    'player'),
('Algeria', 40, 'Mohammed Amoura',      'player'),

-- =============================================
-- ARGENTINA — ARG (41-60)
-- =============================================
('Argentina', 41, 'Escudo Argentina',      'badge'),
('Argentina', 42, 'Emiliano Martínez',     'player'),
('Argentina', 43, 'Nahuel Molina',         'player'),
('Argentina', 44, 'Cristian Romero',       'player'),
('Argentina', 45, 'Nicolás Otamendi',      'player'),
('Argentina', 46, 'Nicolás Tagliafico',    'player'),
('Argentina', 47, 'Leonardo Balerdi',      'player'),
('Argentina', 48, 'Enzo Fernández',        'player'),
('Argentina', 49, 'Alexis Mac Allister',   'player'),
('Argentina', 50, 'Rodrigo De Paul',       'player'),
('Argentina', 51, 'Exequiel Palacios',     'player'),
('Argentina', 52, 'Leandro Paredes',       'player'),
('Argentina', 53, 'Plantel Argentina',     'special'),
('Argentina', 54, 'Nico Paz',              'player'),
('Argentina', 55, 'Franco Mastantuono',    'player'),
('Argentina', 56, 'Nico González',         'player'),
('Argentina', 57, 'Lionel Messi',          'player'),
('Argentina', 58, 'Lautaro Martínez',      'player'),
('Argentina', 59, 'Julián Álvarez',        'player'),
('Argentina', 60, 'Giuliano Simeone',      'player'),

-- =============================================
-- AUSTRALIA — AUS (61-80)
-- =============================================
('Australia', 61, 'Escudo Australia',     'badge'),
('Australia', 62, 'Mathew Ryan',          'player'),
('Australia', 63, 'Joe Gauci',            'player'),
('Australia', 64, 'Harry Souttar',        'player'),
('Australia', 65, 'Alessandro Circati',   'player'),
('Australia', 66, 'Jordan Bos',           'player'),
('Australia', 67, 'Aziz Behich',          'player'),
('Australia', 68, 'Cameron Burgess',      'player'),
('Australia', 69, 'Lewis Miller',         'player'),
('Australia', 70, 'Milos Degenek',        'player'),
('Australia', 71, 'Jackson Irvine',       'player'),
('Australia', 72, 'Riley McGree',         'player'),
('Australia', 73, 'Plantel Australia',    'special'),
('Australia', 74, 'Aiden O''Neill',       'player'),
('Australia', 75, 'Connor Metcalfe',      'player'),
('Australia', 76, 'Patrick Yazbek',       'player'),
('Australia', 77, 'Craig Goodwin',        'player'),
('Australia', 78, 'Kusini Vengi',         'player'),
('Australia', 79, 'Nestory Irankunda',    'player'),
('Australia', 80, 'Mohamed Touré',        'player'),

-- =============================================
-- AUSTRIA — AUT (81-100)
-- =============================================
('Austria', 81,  'Escudo Austria',          'badge'),
('Austria', 82,  'Alexander Schlager',      'player'),
('Austria', 83,  'Patrick Pentz',           'player'),
('Austria', 84,  'David Alaba',             'player'),
('Austria', 85,  'Kevin Danso',             'player'),
('Austria', 86,  'Philipp Lienhart',        'player'),
('Austria', 87,  'Stefan Posch',            'player'),
('Austria', 88,  'Phillipp Mwene',          'player'),
('Austria', 89,  'Alexander Prass',         'player'),
('Austria', 90,  'Xaver Schlager',          'player'),
('Austria', 91,  'Marcel Sabitzer',         'player'),
('Austria', 92,  'Konrad Laimer',           'player'),
('Austria', 93,  'Plantel Austria',         'special'),
('Austria', 94,  'Florian Grillitsch',      'player'),
('Austria', 95,  'Nicolas Seiwald',         'player'),
('Austria', 96,  'Romano Schmid',           'player'),
('Austria', 97,  'Patrick Wimmer',          'player'),
('Austria', 98,  'Christoph Baumgartner',   'player'),
('Austria', 99,  'Michael Gregoritsch',     'player'),
('Austria', 100, 'Marko Arnautović',        'player'),

-- =============================================
-- BÉLGICA — BEL (101-120)
-- =============================================
('Bélgica', 101, 'Escudo Bélgica',          'badge'),
('Bélgica', 102, 'Thibaut Courtois',        'player'),
('Bélgica', 103, 'Arthur Theate',           'player'),
('Bélgica', 104, 'Timothy Castagne',        'player'),
('Bélgica', 105, 'Zeno Debast',             'player'),
('Bélgica', 106, 'Brandon Mechele',         'player'),
('Bélgica', 107, 'Maxim De Cuyper',         'player'),
('Bélgica', 108, 'Thomas Meunier',          'player'),
('Bélgica', 109, 'Youri Tielemans',         'player'),
('Bélgica', 110, 'Amadou Onana',            'player'),
('Bélgica', 111, 'Nicolas Raskin',          'player'),
('Bélgica', 112, 'Alexis Saelemaekers',     'player'),
('Bélgica', 113, 'Plantel Bélgica',         'special'),
('Bélgica', 114, 'Hans Vanaken',            'player'),
('Bélgica', 115, 'Kevin De Bruyne',         'player'),
('Bélgica', 116, 'Jérémy Doku',             'player'),
('Bélgica', 117, 'Charles De Ketelaere',    'player'),
('Bélgica', 118, 'Leandro Trossard',        'player'),
('Bélgica', 119, 'Loïs Openda',             'player'),
('Bélgica', 120, 'Romelu Lukaku',           'player'),

-- =============================================
-- BOSNIA Y HERZEGOVINA — BIH (121-140)
-- =============================================
('Bosnia y Herzegovina', 121, 'Escudo Bosnia y Herzegovina',  'badge'),
('Bosnia y Herzegovina', 122, 'Nikola Vasilj',               'player'),
('Bosnia y Herzegovina', 123, 'Amer Dedic',                  'player'),
('Bosnia y Herzegovina', 124, 'Sead Kolašinac',              'player'),
('Bosnia y Herzegovina', 125, 'Tarik Muharemović',           'player'),
('Bosnia y Herzegovina', 126, 'Nihad Mujakić',               'player'),
('Bosnia y Herzegovina', 127, 'Nikola Katić',                'player'),
('Bosnia y Herzegovina', 128, 'Amir Hadžiahmetović',         'player'),
('Bosnia y Herzegovina', 129, 'Benjamin Tahirović',          'player'),
('Bosnia y Herzegovina', 130, 'Armin Gigović',               'player'),
('Bosnia y Herzegovina', 131, 'Ivan Šunjić',                 'player'),
('Bosnia y Herzegovina', 132, 'Ivan Bašić',                  'player'),
('Bosnia y Herzegovina', 133, 'Plantel Bosnia y Herzegovina', 'special'),
('Bosnia y Herzegovina', 134, 'Dženis Burnić',               'player'),
('Bosnia y Herzegovina', 135, 'Esmir Bajraktarević',         'player'),
('Bosnia y Herzegovina', 136, 'Amar Memić',                  'player'),
('Bosnia y Herzegovina', 137, 'Ermedin Demirović',           'player'),
('Bosnia y Herzegovina', 138, 'Edin Džeko',                  'player'),
('Bosnia y Herzegovina', 139, 'Samed Baždar',                'player'),
('Bosnia y Herzegovina', 140, 'Haris Tabaković',             'player'),

-- =============================================
-- BRASIL — BRA (141-160)
-- =============================================
('Brasil', 141, 'Escudo Brasil',         'badge'),
('Brasil', 142, 'Alisson',               'player'),
('Brasil', 143, 'Bento',                 'player'),
('Brasil', 144, 'Marquinhos',            'player'),
('Brasil', 145, 'Éder Militão',          'player'),
('Brasil', 146, 'Gabriel Magalhães',     'player'),
('Brasil', 147, 'Danilo',               'player'),
('Brasil', 148, 'Wesley',               'player'),
('Brasil', 149, 'Lucas Paquetá',         'player'),
('Brasil', 150, 'Casemiro',              'player'),
('Brasil', 151, 'Bruno Guimarães',       'player'),
('Brasil', 152, 'Luiz Henrique',         'player'),
('Brasil', 153, 'Plantel Brasil',        'special'),
('Brasil', 154, 'Vinicius Júnior',       'player'),
('Brasil', 155, 'Rodrygo',              'player'),
('Brasil', 156, 'João Pedro',           'player'),
('Brasil', 157, 'Matheus Cunha',         'player'),
('Brasil', 158, 'Gabriel Martinelli',    'player'),
('Brasil', 159, 'Raphinha',             'player'),
('Brasil', 160, 'Estévão',              'player'),

-- =============================================
-- CANADÁ — CAN (161-180)
-- =============================================
('Canadá', 161, 'Escudo Canadá',          'badge'),
('Canadá', 162, 'Dayne St. Clair',        'player'),
('Canadá', 163, 'Alphonso Davies',        'player'),
('Canadá', 164, 'Alistair Johnston',      'player'),
('Canadá', 165, 'Samuel Adekugbe',        'player'),
('Canadá', 166, 'Riche Laryea',           'player'),
('Canadá', 167, 'Derek Cornelius',        'player'),
('Canadá', 168, 'Moïse Bombito',          'player'),
('Canadá', 169, 'Kamal Miller',           'player'),
('Canadá', 170, 'Stephen Eustáquio',      'player'),
('Canadá', 171, 'Ismaël Koné',            'player'),
('Canadá', 172, 'Jonathan Osorio',        'player'),
('Canadá', 173, 'Plantel Canadá',         'special'),
('Canadá', 174, 'Jacob Shaffelburg',      'player'),
('Canadá', 175, 'Mathieu Choinière',      'player'),
('Canadá', 176, 'Niko Sigur',             'player'),
('Canadá', 177, 'Tajon Buchanan',         'player'),
('Canadá', 178, 'Liam Millar',            'player'),
('Canadá', 179, 'Cyle Larin',             'player'),
('Canadá', 180, 'Jonathan David',         'player'),

-- =============================================
-- COSTA DE MARFIL — CIV (181-200)
-- =============================================
('Costa de Marfil', 181, 'Escudo Costa de Marfil',   'badge'),
('Costa de Marfil', 182, 'Yahia Fofana',              'player'),
('Costa de Marfil', 183, 'Ghislain Konan',            'player'),
('Costa de Marfil', 184, 'Wilfried Singo',            'player'),
('Costa de Marfil', 185, 'Odilon Kossounou',          'player'),
('Costa de Marfil', 186, 'Evan N''Dicka',             'player'),
('Costa de Marfil', 187, 'Willy Boly',                'player'),
('Costa de Marfil', 188, 'Emmanuel Agbadou',          'player'),
('Costa de Marfil', 189, 'Ousmane Diomandé',          'player'),
('Costa de Marfil', 190, 'Franck Kessié',             'player'),
('Costa de Marfil', 191, 'Seko Fofana',               'player'),
('Costa de Marfil', 192, 'Ibrahim Sangaré',           'player'),
('Costa de Marfil', 193, 'Plantel Costa de Marfil',   'special'),
('Costa de Marfil', 194, 'Jean-Philippe Gbamin',      'player'),
('Costa de Marfil', 195, 'Amad Diallo',               'player'),
('Costa de Marfil', 196, 'Sébastien Haller',          'player'),
('Costa de Marfil', 197, 'Simon Adingra',             'player'),
('Costa de Marfil', 198, 'Yan Diomandé',              'player'),
('Costa de Marfil', 199, 'Evann Guessand',            'player'),
('Costa de Marfil', 200, 'Oumar Diakité',             'player'),

-- =============================================
-- CONGO DR — COD (201-220)
-- =============================================
('Congo DR', 201, 'Escudo Congo DR',         'badge'),
('Congo DR', 202, 'Lionel Mpasi',            'player'),
('Congo DR', 203, 'Aaron Wan-Bissaka',       'player'),
('Congo DR', 204, 'Axel Tuanzebe',           'player'),
('Congo DR', 205, 'Arthur Masuaku',          'player'),
('Congo DR', 206, 'Chancel Mbemba',          'player'),
('Congo DR', 207, 'Joris Kayembe',           'player'),
('Congo DR', 208, 'Charles Pickel',          'player'),
('Congo DR', 209, 'Ngal''ayel Mukau',        'player'),
('Congo DR', 210, 'Edo Kayembe',             'player'),
('Congo DR', 211, 'Samuel Moutoussamy',      'player'),
('Congo DR', 212, 'Noah Sadiki',             'player'),
('Congo DR', 213, 'Plantel Congo DR',        'special'),
('Congo DR', 214, 'Théo Bongonda',           'player'),
('Congo DR', 215, 'Meschak Elia',            'player'),
('Congo DR', 216, 'Yoane Wissa',             'player'),
('Congo DR', 217, 'Brian Cipenga',           'player'),
('Congo DR', 218, 'Fiston Mayele',           'player'),
('Congo DR', 219, 'Cédric Bakambu',          'player'),
('Congo DR', 220, 'Nathanaël Mbuku',         'player'),

-- =============================================
-- COLOMBIA — COL (221-240)
-- =============================================
('Colombia', 221, 'Escudo Colombia',          'badge'),
('Colombia', 222, 'Camilo Vargas',            'player'),
('Colombia', 223, 'David Ospina',             'player'),
('Colombia', 224, 'Dávinson Sánchez',         'player'),
('Colombia', 225, 'Yerry Mina',               'player'),
('Colombia', 226, 'Daniel Muñoz',             'player'),
('Colombia', 227, 'Johan Mojica',             'player'),
('Colombia', 228, 'Jhon Lucumí',              'player'),
('Colombia', 229, 'Santiago Arias',           'player'),
('Colombia', 230, 'Jefferson Lerma',          'player'),
('Colombia', 231, 'Kevin Castaño',            'player'),
('Colombia', 232, 'Richard Ríos',             'player'),
('Colombia', 233, 'Plantel Colombia',         'special'),
('Colombia', 234, 'James Rodríguez',          'player'),
('Colombia', 235, 'Juan Fernando Quintero',   'player'),
('Colombia', 236, 'Jorge Carrascal',          'player'),
('Colombia', 237, 'Jon Arias',               'player'),
('Colombia', 238, 'Jhon Córdoba',             'player'),
('Colombia', 239, 'Luis Suárez',              'player'),
('Colombia', 240, 'Luis Díaz',               'player'),

-- =============================================
-- CABO VERDE — CPV (241-260)
-- =============================================
('Cabo Verde', 241, 'Escudo Cabo Verde',      'badge'),
('Cabo Verde', 242, 'Vozinha',               'player'),
('Cabo Verde', 243, 'Logan Costa',           'player'),
('Cabo Verde', 244, 'Pico',                  'player'),
('Cabo Verde', 245, 'Diney',                 'player'),
('Cabo Verde', 246, 'Steven Moreira',        'player'),
('Cabo Verde', 247, 'Wagner Pina',           'player'),
('Cabo Verde', 248, 'Joao Paulo',            'player'),
('Cabo Verde', 249, 'Yannick Semedo',        'player'),
('Cabo Verde', 250, 'Kevin Pina',            'player'),
('Cabo Verde', 251, 'Patrick Andrade',       'player'),
('Cabo Verde', 252, 'Jamiro Monteiro',       'player'),
('Cabo Verde', 253, 'Plantel Cabo Verde',    'special'),
('Cabo Verde', 254, 'Deroy Duarte',          'player'),
('Cabo Verde', 255, 'Garry Rodrigues',       'player'),
('Cabo Verde', 256, 'Jovane Cabral',         'player'),
('Cabo Verde', 257, 'Ryan Mendes',           'player'),
('Cabo Verde', 258, 'Dailon Livramento',     'player'),
('Cabo Verde', 259, 'Willy Semedo',          'player'),
('Cabo Verde', 260, 'Bebé',                  'player'),

-- =============================================
-- CROACIA — CRO (261-280)
-- =============================================
('Croacia', 261, 'Escudo Croacia',          'badge'),
('Croacia', 262, 'Dominik Livaković',       'player'),
('Croacia', 263, 'Duje Ćaleta-Car',         'player'),
('Croacia', 264, 'Joško Gvardiol',          'player'),
('Croacia', 265, 'Josip Stanišić',          'player'),
('Croacia', 266, 'Luka Vušković',           'player'),
('Croacia', 267, 'Josip Šutalo',            'player'),
('Croacia', 268, 'Kristijan Jakić',         'player'),
('Croacia', 269, 'Luka Modrić',             'player'),
('Croacia', 270, 'Mateo Kovačić',           'player'),
('Croacia', 271, 'Martin Baturina',         'player'),
('Croacia', 272, 'Lovro Majer',             'player'),
('Croacia', 273, 'Plantel Croacia',         'special'),
('Croacia', 274, 'Mario Pašalić',           'player'),
('Croacia', 275, 'Petar Sučić',             'player'),
('Croacia', 276, 'Ivan Perišić',            'player'),
('Croacia', 277, 'Marco Pašalić',           'player'),
('Croacia', 278, 'Ante Budimir',            'player'),
('Croacia', 279, 'Andrej Kramarić',         'player'),
('Croacia', 280, 'Franjo Ivanović',         'player'),

-- =============================================
-- CURAÇAO — CUW (281-300)
-- =============================================
('Curaçao', 281, 'Escudo Curaçao',          'badge'),
('Curaçao', 282, 'Eloy Room',               'player'),
('Curaçao', 283, 'Armando Obispo',          'player'),
('Curaçao', 284, 'Sherel Floranus',         'player'),
('Curaçao', 285, 'Jurien Gaari',            'player'),
('Curaçao', 286, 'Joshua Brenet',           'player'),
('Curaçao', 287, 'Roshon Van Eijma',        'player'),
('Curaçao', 288, 'Shurandy Sambo',          'player'),
('Curaçao', 289, 'Livano Comenencia',       'player'),
('Curaçao', 290, 'Godfried Roemeratoe',     'player'),
('Curaçao', 291, 'Juninho Bacuna',          'player'),
('Curaçao', 292, 'Leandro Bacuna',          'player'),
('Curaçao', 293, 'Plantel Curaçao',         'special'),
('Curaçao', 294, 'Tahith Chong',            'player'),
('Curaçao', 295, 'Kenji Gorre',             'player'),
('Curaçao', 296, 'Jearl Margaritha',        'player'),
('Curaçao', 297, 'Jurgen Locadia',          'player'),
('Curaçao', 298, 'Jeremy Antonisse',        'player'),
('Curaçao', 299, 'Gervane Kastaneer',       'player'),
('Curaçao', 300, 'Sontje Hansen',           'player'),

-- =============================================
-- CHEQUIA — CZE (301-320)
-- =============================================
('Chequia', 301, 'Escudo Chequia',           'badge'),
('Chequia', 302, 'Matej Kovář',              'player'),
('Chequia', 303, 'Jindřich Staněk',          'player'),
('Chequia', 304, 'Ladislav Krejčí',          'player'),
('Chequia', 305, 'Vladimír Coufal',          'player'),
('Chequia', 306, 'Jaroslav Zelený',          'player'),
('Chequia', 307, 'Tomáš Holeš',              'player'),
('Chequia', 308, 'David Zima',               'player'),
('Chequia', 309, 'Michal Sadílek',           'player'),
('Chequia', 310, 'Lukáš Provod',             'player'),
('Chequia', 311, 'Lukáš Červ',               'player'),
('Chequia', 312, 'Tomáš Souček',             'player'),
('Chequia', 313, 'Plantel Chequia',          'special'),
('Chequia', 314, 'Pavel Šulc',               'player'),
('Chequia', 315, 'Matěj Vydra',              'player'),
('Chequia', 316, 'Vasil Kušej',              'player'),
('Chequia', 317, 'Tomáš Chorý',              'player'),
('Chequia', 318, 'Václav Černý',             'player'),
('Chequia', 319, 'Adam Hložek',              'player'),
('Chequia', 320, 'Patrik Schick',            'player'),

-- =============================================
-- ECUADOR — ECU (321-340)
-- =============================================
('Ecuador', 321, 'Escudo Ecuador',          'badge'),
('Ecuador', 322, 'Hernán Galíndez',         'player'),
('Ecuador', 323, 'Gonzalo Valle',           'player'),
('Ecuador', 324, 'Piero Hincapié',          'player'),
('Ecuador', 325, 'Pervis Estupiñán',        'player'),
('Ecuador', 326, 'Willian Pacho',           'player'),
('Ecuador', 327, 'Ángelo Preciado',         'player'),
('Ecuador', 328, 'Joel Ordóñez',            'player'),
('Ecuador', 329, 'Moisés Caicedo',          'player'),
('Ecuador', 330, 'Alan Franco',             'player'),
('Ecuador', 331, 'Kendry Páez',             'player'),
('Ecuador', 332, 'Pedro Vite',              'player'),
('Ecuador', 333, 'Plantel Ecuador',         'special'),
('Ecuador', 334, 'John Yeboah',             'player'),
('Ecuador', 335, 'Leonardo Campana',        'player'),
('Ecuador', 336, 'Gonzalo Plata',           'player'),
('Ecuador', 337, 'Nilson Angulo',           'player'),
('Ecuador', 338, 'Alan Minda',              'player'),
('Ecuador', 339, 'Kevin Rodríguez',         'player'),
('Ecuador', 340, 'Enner Valencia',          'player'),

-- =============================================
-- EGIPTO — EGY (341-360)
-- =============================================
('Egipto', 341, 'Escudo Egipto',            'badge'),
('Egipto', 342, 'Mohamed El-Shenawy',       'player'),
('Egipto', 343, 'Mohamed Hany',             'player'),
('Egipto', 344, 'Mohamed Hamdy',            'player'),
('Egipto', 345, 'Yasser Ibrahim',           'player'),
('Egipto', 346, 'Khaled Sobhi',             'player'),
('Egipto', 347, 'Ramy Rabia',               'player'),
('Egipto', 348, 'Hossam Abdelmaguid',       'player'),
('Egipto', 349, 'Ahmed Fatouh',             'player'),
('Egipto', 350, 'Marwan Attia',             'player'),
('Egipto', 351, 'Zizo',                     'player'),
('Egipto', 352, 'Hamdy Fathy',              'player'),
('Egipto', 353, 'Plantel Egipto',           'special'),
('Egipto', 354, 'Mohamed Lasheen',          'player'),
('Egipto', 355, 'Emam Ashour',              'player'),
('Egipto', 356, 'Osama Faisal',             'player'),
('Egipto', 357, 'Mohamed Salah',            'player'),
('Egipto', 358, 'Mostafa Mohamed',          'player'),
('Egipto', 359, 'Trézéguet',               'player'),
('Egipto', 360, 'Omar Marmoush',            'player'),

-- =============================================
-- INGLATERRA — ENG (361-380)
-- =============================================
('Inglaterra', 361, 'Escudo Inglaterra',       'badge'),
('Inglaterra', 362, 'Jordan Pickford',         'player'),
('Inglaterra', 363, 'John Stones',             'player'),
('Inglaterra', 364, 'Marc Guéhi',              'player'),
('Inglaterra', 365, 'Ezri Konsa',              'player'),
('Inglaterra', 366, 'Trent Alexander-Arnold',  'player'),
('Inglaterra', 367, 'Reece James',             'player'),
('Inglaterra', 368, 'Dan Burn',                'player'),
('Inglaterra', 369, 'Jordan Henderson',        'player'),
('Inglaterra', 370, 'Declan Rice',             'player'),
('Inglaterra', 371, 'Jude Bellingham',         'player'),
('Inglaterra', 372, 'Cole Palmer',             'player'),
('Inglaterra', 373, 'Plantel Inglaterra',      'special'),
('Inglaterra', 374, 'Morgan Rogers',           'player'),
('Inglaterra', 375, 'Anthony Gordon',          'player'),
('Inglaterra', 376, 'Phil Foden',              'player'),
('Inglaterra', 377, 'Bukayo Saka',             'player'),
('Inglaterra', 378, 'Harry Kane',              'player'),
('Inglaterra', 379, 'Marcus Rashford',         'player'),
('Inglaterra', 380, 'Ollie Watkins',           'player'),

-- =============================================
-- ESPAÑA — ESP (381-400)
-- =============================================
('España', 381, 'Escudo España',          'badge'),
('España', 382, 'Unai Simón',             'player'),
('España', 383, 'Robin Le Normand',       'player'),
('España', 384, 'Aymeric Laporte',        'player'),
('España', 385, 'Dean Huijsen',           'player'),
('España', 386, 'Pedro Porro',            'player'),
('España', 387, 'Dani Carvajal',          'player'),
('España', 388, 'Marc Cucurella',         'player'),
('España', 389, 'Martín Zubimendi',       'player'),
('España', 390, 'Rodri',                  'player'),
('España', 391, 'Pedri',                  'player'),
('España', 392, 'Fabián Ruiz',            'player'),
('España', 393, 'Plantel España',         'special'),
('España', 394, 'Mikel Merino',           'player'),
('España', 395, 'Lamine Yamal',           'player'),
('España', 396, 'Dani Olmo',              'player'),
('España', 397, 'Nico Williams',          'player'),
('España', 398, 'Ferran Torres',          'player'),
('España', 399, 'Álvaro Morata',          'player'),
('España', 400, 'Mikel Oyarzabal',        'player'),

-- =============================================
-- FRANCIA — FRA (401-420)
-- =============================================
('Francia', 401, 'Escudo Francia',          'badge'),
('Francia', 402, 'Mike Maignan',            'player'),
('Francia', 403, 'Théo Hernández',          'player'),
('Francia', 404, 'William Saliba',          'player'),
('Francia', 405, 'Jules Koundé',            'player'),
('Francia', 406, 'Ibrahima Konaté',         'player'),
('Francia', 407, 'Dayot Upamecano',         'player'),
('Francia', 408, 'Lucas Digne',             'player'),
('Francia', 409, 'Aurélien Tchouaméni',     'player'),
('Francia', 410, 'Eduardo Camavinga',       'player'),
('Francia', 411, 'Manu Koné',               'player'),
('Francia', 412, 'Adrien Rabiot',           'player'),
('Francia', 413, 'Plantel Francia',         'special'),
('Francia', 414, 'Michaël Olise',           'player'),
('Francia', 415, 'Ousmane Dembélé',         'player'),
('Francia', 416, 'Bradley Barcola',         'player'),
('Francia', 417, 'Désiré Doué',             'player'),
('Francia', 418, 'Kingsley Coman',          'player'),
('Francia', 419, 'Hugo Ekitike',            'player'),
('Francia', 420, 'Kylian Mbappé',           'player'),

-- =============================================
-- ALEMANIA — GER (421-440)
-- =============================================
('Alemania', 421, 'Escudo Alemania',          'badge'),
('Alemania', 422, 'Marc-André ter Stegen',    'player'),
('Alemania', 423, 'Jonathan Tah',             'player'),
('Alemania', 424, 'David Raum',               'player'),
('Alemania', 425, 'Nico Schlotterbeck',       'player'),
('Alemania', 426, 'Antonio Rüdiger',          'player'),
('Alemania', 427, 'Waldemar Anton',           'player'),
('Alemania', 428, 'Ridle Baku',               'player'),
('Alemania', 429, 'Maximilian Mittelstädt',   'player'),
('Alemania', 430, 'Joshua Kimmich',           'player'),
('Alemania', 431, 'Florian Wirtz',            'player'),
('Alemania', 432, 'Felix Nmecha',             'player'),
('Alemania', 433, 'Plantel Alemania',         'special'),
('Alemania', 434, 'Leon Goretzka',            'player'),
('Alemania', 435, 'Jamal Musiala',            'player'),
('Alemania', 436, 'Serge Gnabry',             'player'),
('Alemania', 437, 'Kai Havertz',              'player'),
('Alemania', 438, 'Leroy Sané',               'player'),
('Alemania', 439, 'Karim Adeyemi',            'player'),
('Alemania', 440, 'Nick Woltemade',           'player'),

-- =============================================
-- GHANA — GHA (441-460)
-- =============================================
('Ghana', 441, 'Escudo Ghana',              'badge'),
('Ghana', 442, 'Lawrence Ati-Zigi',         'player'),
('Ghana', 443, 'Tariq Lamptey',             'player'),
('Ghana', 444, 'Mohammed Salisu',           'player'),
('Ghana', 445, 'Alidu Seidu',               'player'),
('Ghana', 446, 'Alexander Djiku',           'player'),
('Ghana', 447, 'Gideon Mensah',             'player'),
('Ghana', 448, 'Caleb Yirenkyi',            'player'),
('Ghana', 449, 'Abdul Issahaku Fatawu',     'player'),
('Ghana', 450, 'Thomas Partey',             'player'),
('Ghana', 451, 'Salis Abdul Samed',         'player'),
('Ghana', 452, 'Kamaldeen Sulemana',        'player'),
('Ghana', 453, 'Plantel Ghana',             'special'),
('Ghana', 454, 'Mohammed Kudus',            'player'),
('Ghana', 455, 'Iñaki Williams',            'player'),
('Ghana', 456, 'Jordan Ayew',               'player'),
('Ghana', 457, 'Andrew Ayew',               'player'),
('Ghana', 458, 'Joseph Paintsil',           'player'),
('Ghana', 459, 'Osman Bukari',              'player'),
('Ghana', 460, 'Antoine Semenyo',           'player'),

-- =============================================
-- HAITÍ — HAI (461-480)
-- =============================================
('Haití', 461, 'Escudo Haití',              'badge'),
('Haití', 462, 'Johny Placide',             'player'),
('Haití', 463, 'Carlens Arcus',             'player'),
('Haití', 464, 'Martin Expérience',         'player'),
('Haití', 465, 'Jean-Kevin Duverne',        'player'),
('Haití', 466, 'Ricardo Adé',               'player'),
('Haití', 467, 'Duke Lacroix',              'player'),
('Haití', 468, 'Garven Metusala',           'player'),
('Haití', 469, 'Hannes Delcroix',           'player'),
('Haití', 470, 'Leverton Pierre',           'player'),
('Haití', 471, 'Danley Jean Jacques',       'player'),
('Haití', 472, 'Jean-Ricner Bellegarde',    'player'),
('Haití', 473, 'Plantel Haití',             'special'),
('Haití', 474, 'Christopher Attys',         'player'),
('Haití', 475, 'Derrick Etienne Jr.',       'player'),
('Haití', 476, 'Josué Casimir',             'player'),
('Haití', 477, 'Ruben Providence',          'player'),
('Haití', 478, 'Duckens Nazon',             'player'),
('Haití', 479, 'Louicius Deedson',          'player'),
('Haití', 480, 'Frantzdy Pierrot',          'player'),

-- =============================================
-- IRÁN — IRN (481-500)
-- =============================================
('Irán', 481, 'Escudo Irán',              'badge'),
('Irán', 482, 'Alireza Beiranvand',       'player'),
('Irán', 483, 'Morteza Pouraliganji',     'player'),
('Irán', 484, 'Ehsan Hajsafi',            'player'),
('Irán', 485, 'Milad Mohammadi',          'player'),
('Irán', 486, 'Shojae Khalilzadeh',       'player'),
('Irán', 487, 'Ramin Rezaeian',           'player'),
('Irán', 488, 'Hossein Kanaani',          'player'),
('Irán', 489, 'Sadegh Moharrami',         'player'),
('Irán', 490, 'Saleh Hardani',            'player'),
('Irán', 491, 'Saeed Ezatolahi',          'player'),
('Irán', 492, 'Saman Ghoddos',            'player'),
('Irán', 493, 'Plantel Irán',             'special'),
('Irán', 494, 'Omid Noorafkan',           'player'),
('Irán', 495, 'Roozbeh Cheshmi',          'player'),
('Irán', 496, 'Mohammad Mohebi',          'player'),
('Irán', 497, 'Sardar Azmoun',            'player'),
('Irán', 498, 'Mehdi Taremi',             'player'),
('Irán', 499, 'Alireza Jahanbakhsh',      'player'),
('Irán', 500, 'Ali Gholizadeh',           'player'),

-- =============================================
-- IRAK — IRQ (501-520)
-- =============================================
('Irak', 501, 'Escudo Irak',           'badge'),
('Irak', 502, 'Jalal Hassan',          'player'),
('Irak', 503, 'Rebin Sulaka',          'player'),
('Irak', 504, 'Hussein Ali',           'player'),
('Irak', 505, 'Akam Hashem',           'player'),
('Irak', 506, 'Merchas Doski',         'player'),
('Irak', 507, 'Zaid Tahseen',          'player'),
('Irak', 508, 'Manaf Younis',          'player'),
('Irak', 509, 'Zidane Iqbal',          'player'),
('Irak', 510, 'Amir Al-Ammari',        'player'),
('Irak', 511, 'Ibrahim Bavesh',        'player'),
('Irak', 512, 'Ali Jasim',             'player'),
('Irak', 513, 'Plantel Irak',          'special'),
('Irak', 514, 'Youssef Amyn',          'player'),
('Irak', 515, 'Aimar Sher',            'player'),
('Irak', 516, 'Marko Farji',           'player'),
('Irak', 517, 'Osama Rashid',          'player'),
('Irak', 518, 'Ali Al-Hamadi',         'player'),
('Irak', 519, 'Aymen Hussein',         'player'),
('Irak', 520, 'Mohannad Ali',          'player'),

-- =============================================
-- JORDANIA — JOR (521-540)
-- =============================================
('Jordania', 521, 'Escudo Jordania',          'badge'),
('Jordania', 522, 'Yazeed Abulaila',          'player'),
('Jordania', 523, 'Ihsan Haddad',             'player'),
('Jordania', 524, 'Mohammad Abu Hashish',     'player'),
('Jordania', 525, 'Yazan Al-Arab',            'player'),
('Jordania', 526, 'Abdallah Nasib',           'player'),
('Jordania', 527, 'Saleem Obaid',             'player'),
('Jordania', 528, 'Mohammad Abualnadi',       'player'),
('Jordania', 529, 'Ibrahim Saadeh',           'player'),
('Jordania', 530, 'Nizar Al-Rashdan',         'player'),
('Jordania', 531, 'Noor Al-Rawabdeh',         'player'),
('Jordania', 532, 'Mohannad Abu Taha',        'player'),
('Jordania', 533, 'Plantel Jordania',         'special'),
('Jordania', 534, 'Amer Jamous',              'player'),
('Jordania', 535, 'Musa Al-Taamari',          'player'),
('Jordania', 536, 'Yazan Al-Naimat',          'player'),
('Jordania', 537, 'Mahmoud Al-Mardi',         'player'),
('Jordania', 538, 'Ali Olwan',                'player'),
('Jordania', 539, 'Mohammad Abu Zrayq',       'player'),
('Jordania', 540, 'Ibrahim Sabra',            'player'),

-- =============================================
-- JAPÓN — JPN (541-560)
-- =============================================
('Japón', 541, 'Escudo Japón',           'badge'),
('Japón', 542, 'Zion Suzuki',            'player'),
('Japón', 543, 'Henry H. Mochizuki',     'player'),
('Japón', 544, 'Ayumu Seko',             'player'),
('Japón', 545, 'Junnosuke Suzuki',       'player'),
('Japón', 546, 'Shogo Taniguchi',        'player'),
('Japón', 547, 'Tsuyoshi Watanabe',      'player'),
('Japón', 548, 'Kaishu Sano',            'player'),
('Japón', 549, 'Yuki Soma',              'player'),
('Japón', 550, 'Ao Tanaka',              'player'),
('Japón', 551, 'Daichi Kamada',          'player'),
('Japón', 552, 'Takefusa Kubo',          'player'),
('Japón', 553, 'Plantel Japón',          'special'),
('Japón', 554, 'Ritsu Doan',             'player'),
('Japón', 555, 'Keito Nakamura',         'player'),
('Japón', 556, 'Takumi Minamino',        'player'),
('Japón', 557, 'Shuto Machino',          'player'),
('Japón', 558, 'Junya Ito',              'player'),
('Japón', 559, 'Koki Ogawa',             'player'),
('Japón', 560, 'Ayase Ueda',             'player'),

-- =============================================
-- COREA DEL SUR — KOR (561-580)
-- =============================================
('Corea del Sur', 561, 'Escudo Corea del Sur',   'badge'),
('Corea del Sur', 562, 'Hyeon-woo Jo',           'player'),
('Corea del Sur', 563, 'Seung-gyu Kim',          'player'),
('Corea del Sur', 564, 'Min-jae Kim',            'player'),
('Corea del Sur', 565, 'Yu-min Cho',             'player'),
('Corea del Sur', 566, 'Young-woo Seol',         'player'),
('Corea del Sur', 567, 'Han-beom Lee',           'player'),
('Corea del Sur', 568, 'Tae-seok Lee',           'player'),
('Corea del Sur', 569, 'Myung-jae Lee',          'player'),
('Corea del Sur', 570, 'Jae-sung Lee',           'player'),
('Corea del Sur', 571, 'In-beom Hwang',          'player'),
('Corea del Sur', 572, 'Kang-in Lee',            'player'),
('Corea del Sur', 573, 'Plantel Corea del Sur',  'special'),
('Corea del Sur', 574, 'Seung-ho Paik',          'player'),
('Corea del Sur', 575, 'Jens Castrop',           'player'),
('Corea del Sur', 576, 'Dong-yeong Lee',         'player'),
('Corea del Sur', 577, 'Gue-sung Cho',           'player'),
('Corea del Sur', 578, 'Heung-min Son',          'player'),
('Corea del Sur', 579, 'Hee-chan Hwang',         'player'),
('Corea del Sur', 580, 'Hyeon-gyu Oh',           'player'),

-- =============================================
-- ARABIA SAUDITA — KSA (581-600)
-- =============================================
('Arabia Saudita', 581, 'Escudo Arabia Saudita',   'badge'),
('Arabia Saudita', 582, 'Nawaf Al-Aqidi',          'player'),
('Arabia Saudita', 583, 'Abdulrahman Al-Sanbi',    'player'),
('Arabia Saudita', 584, 'Saud Abdulhamid',         'player'),
('Arabia Saudita', 585, 'Nawaf Bouwashl',          'player'),
('Arabia Saudita', 586, 'Jihad Thakri',            'player'),
('Arabia Saudita', 587, 'Moteb Al-Harbi',          'player'),
('Arabia Saudita', 588, 'Hassan Al-Tambakti',      'player'),
('Arabia Saudita', 589, 'Musab Al-Juwayr',         'player'),
('Arabia Saudita', 590, 'Ziyad Al-Johani',         'player'),
('Arabia Saudita', 591, 'Abdullah Al-Khaibari',    'player'),
('Arabia Saudita', 592, 'Nasser Al-Dawsari',       'player'),
('Arabia Saudita', 593, 'Plantel Arabia Saudita',  'special'),
('Arabia Saudita', 594, 'Saleh Abu Alshamat',      'player'),
('Arabia Saudita', 595, 'Marwan Al-Sahafi',        'player'),
('Arabia Saudita', 596, 'Salem Al-Dawsari',        'player'),
('Arabia Saudita', 597, 'Abdulrahman Al-Aboud',    'player'),
('Arabia Saudita', 598, 'Feras Al-Buraikan',       'player'),
('Arabia Saudita', 599, 'Saleh Al-Shehri',         'player'),
('Arabia Saudita', 600, 'Abdullah Al-Hamdan',      'player'),

-- =============================================
-- MARRUECOS — MAR (601-620)
-- =============================================
('Marruecos', 601, 'Escudo Marruecos',        'badge'),
('Marruecos', 602, 'Yassine Bounou "Bono"',   'player'),
('Marruecos', 603, 'Munir El Kajoui',         'player'),
('Marruecos', 604, 'Achraf Hakimi',           'player'),
('Marruecos', 605, 'Noussair Mazraoui',       'player'),
('Marruecos', 606, 'Nayef Aguerd',            'player'),
('Marruecos', 607, 'Romain Saïss',            'player'),
('Marruecos', 608, 'Jawad El Yamiq',          'player'),
('Marruecos', 609, 'Adam Masina',             'player'),
('Marruecos', 610, 'Sofyan Amrabat',          'player'),
('Marruecos', 611, 'Azzedine Ounahi',         'player'),
('Marruecos', 612, 'Eliesse Ben Seghir',      'player'),
('Marruecos', 613, 'Plantel Marruecos',       'special'),
('Marruecos', 614, 'Bilal El Khannous',       'player'),
('Marruecos', 615, 'Ismael Saibari',          'player'),
('Marruecos', 616, 'Youssef En-Nesyri',       'player'),
('Marruecos', 617, 'Abde Ezzalzouli',         'player'),
('Marruecos', 618, 'Soufiane Rahimi',         'player'),
('Marruecos', 619, 'Brahim Díaz',             'player'),
('Marruecos', 620, 'Ayoub El Kaabi',          'player'),

-- =============================================
-- MÉXICO — MEX (621-640)
-- =============================================
('México', 621, 'Escudo México',           'badge'),
('México', 622, 'Luis Malagón',            'player'),
('México', 623, 'Johan Vásquez',           'player'),
('México', 624, 'Jorge Sánchez',           'player'),
('México', 625, 'César Montes',            'player'),
('México', 626, 'Jesús Gallardo',          'player'),
('México', 627, 'Israel Reyes',            'player'),
('México', 628, 'Diego Lainez',            'player'),
('México', 629, 'Carlos Rodríguez',        'player'),
('México', 630, 'Edson Álvarez',           'player'),
('México', 631, 'Orbelin Pineda',          'player'),
('México', 632, 'Marcel Ruiz',             'player'),
('México', 633, 'Plantel México',          'special'),
('México', 634, 'Érick Sánchez',           'player'),
('México', 635, 'Hirving "Chucky" Lozano', 'player'),
('México', 636, 'Santiago Giménez',        'player'),
('México', 637, 'Raúl Jiménez',            'player'),
('México', 638, 'Alexis Vega',             'player'),
('México', 639, 'Roberto Alvarado',        'player'),
('México', 640, 'César Huerta',            'player'),

-- =============================================
-- PAÍSES BAJOS — NED (641-660)
-- =============================================
('Países Bajos', 641, 'Escudo Países Bajos',   'badge'),
('Países Bajos', 642, 'Bart Verbruggen',       'player'),
('Países Bajos', 643, 'Virgil van Dijk',       'player'),
('Países Bajos', 644, 'Micky van de Ven',      'player'),
('Países Bajos', 645, 'Jurriën Timber',        'player'),
('Países Bajos', 646, 'Denzel Dumfries',       'player'),
('Países Bajos', 647, 'Nathan Aké',            'player'),
('Países Bajos', 648, 'Jeremie Frimpong',      'player'),
('Países Bajos', 649, 'Jan Paul van Hecke',    'player'),
('Países Bajos', 650, 'Tijjani Reijnders',     'player'),
('Países Bajos', 651, 'Ryan Gravenberch',      'player'),
('Países Bajos', 652, 'Teun Koopmeiners',      'player'),
('Países Bajos', 653, 'Plantel Países Bajos',  'special'),
('Países Bajos', 654, 'Frenkie de Jong',       'player'),
('Países Bajos', 655, 'Xavi Simons',           'player'),
('Países Bajos', 656, 'Justin Kluivert',       'player'),
('Países Bajos', 657, 'Memphis Depay',         'player'),
('Países Bajos', 658, 'Donyell Malen',         'player'),
('Países Bajos', 659, 'Wout Weghorst',         'player'),
('Países Bajos', 660, 'Cody Gakpo',            'player'),

-- =============================================
-- NORUEGA — NOR (661-680)
-- =============================================
('Noruega', 661, 'Escudo Noruega',              'badge'),
('Noruega', 662, 'Ørjan Nyland',                'player'),
('Noruega', 663, 'Julian Ryerson',              'player'),
('Noruega', 664, 'Leo Østigård',                'player'),
('Noruega', 665, 'Kristoffer Vassbakk Ajer',    'player'),
('Noruega', 666, 'Marcus Holmgren Pedersen',    'player'),
('Noruega', 667, 'David Møller Wolfe',          'player'),
('Noruega', 668, 'Torbjørn Heggem',             'player'),
('Noruega', 669, 'Morten Thorsby',              'player'),
('Noruega', 670, 'Martin Ødegaard',             'player'),
('Noruega', 671, 'Sander Berge',                'player'),
('Noruega', 672, 'Andreas Schjelderup',         'player'),
('Noruega', 673, 'Plantel Noruega',             'special'),
('Noruega', 674, 'Patrick Berg',                'player'),
('Noruega', 675, 'Erling Haaland',              'player'),
('Noruega', 676, 'Alexander Sørloth',           'player'),
('Noruega', 677, 'Aron Dønnum',                 'player'),
('Noruega', 678, 'Jørgen Strand Larsen',        'player'),
('Noruega', 679, 'Antonio Nusa',                'player'),
('Noruega', 680, 'Oscar Bobb',                  'player'),

-- =============================================
-- NUEVA ZELANDA — NZL (681-700)
-- =============================================
('Nueva Zelanda', 681, 'Escudo Nueva Zelanda',   'badge'),
('Nueva Zelanda', 682, 'Max Crocombe',           'player'),
('Nueva Zelanda', 683, 'Alex Paulsen',           'player'),
('Nueva Zelanda', 684, 'Michael Boxall',         'player'),
('Nueva Zelanda', 685, 'Liberato Cacace',        'player'),
('Nueva Zelanda', 686, 'Tim Payne',              'player'),
('Nueva Zelanda', 687, 'Tyler Bindon',           'player'),
('Nueva Zelanda', 688, 'Francis de Vries',       'player'),
('Nueva Zelanda', 689, 'Finn Surman',            'player'),
('Nueva Zelanda', 690, 'Joe Bell',               'player'),
('Nueva Zelanda', 691, 'Sarpreet Singh',         'player'),
('Nueva Zelanda', 692, 'Ryan Thomas',            'player'),
('Nueva Zelanda', 693, 'Plantel Nueva Zelanda',  'special'),
('Nueva Zelanda', 694, 'Matthew Garbett',        'player'),
('Nueva Zelanda', 695, 'Marko Stamenić',         'player'),
('Nueva Zelanda', 696, 'Ben Old',                'player'),
('Nueva Zelanda', 697, 'Chris Wood',             'player'),
('Nueva Zelanda', 698, 'Elijah Just',            'player'),
('Nueva Zelanda', 699, 'Callum McCowatt',        'player'),
('Nueva Zelanda', 700, 'Kosta Barbarouses',      'player'),

-- =============================================
-- PANAMÁ — PAN (701-720)
-- =============================================
('Panamá', 701, 'Escudo Panamá',             'badge'),
('Panamá', 702, 'Orlando Mosquera',          'player'),
('Panamá', 703, 'Luis Mejía',                'player'),
('Panamá', 704, 'Fidel Escobar',             'player'),
('Panamá', 705, 'Andrés Andrade',            'player'),
('Panamá', 706, 'Michael Amir Murillo',      'player'),
('Panamá', 707, 'Eric Davis',                'player'),
('Panamá', 708, 'José Córdoba',              'player'),
('Panamá', 709, 'César Blackman',            'player'),
('Panamá', 710, 'Cristian Martínez',         'player'),
('Panamá', 711, 'Aníbal Godoy',              'player'),
('Panamá', 712, 'Adalberto Carrasquilla',    'player'),
('Panamá', 713, 'Plantel Panamá',            'special'),
('Panamá', 714, 'Édgar Bárcenas',            'player'),
('Panamá', 715, 'Carlos Harvey',             'player'),
('Panamá', 716, 'Ismael Díaz',               'player'),
('Panamá', 717, 'José Fajardo',              'player'),
('Panamá', 718, 'Cecilio Waterman',          'player'),
('Panamá', 719, 'José Luiz Rodríguez',       'player'),
('Panamá', 720, 'Alberto Quintero',          'player'),

-- =============================================
-- PARAGUAY — PAR (721-740)
-- =============================================
('Paraguay', 721, 'Escudo Paraguay',                    'badge'),
('Paraguay', 722, 'Roberto Fernández',                  'player'),
('Paraguay', 723, 'Orlando Gill',                       'player'),
('Paraguay', 724, 'Gustavo Gómez',                      'player'),
('Paraguay', 725, 'Fabián Balbuena',                    'player'),
('Paraguay', 726, 'Juan José Cáceres',                  'player'),
('Paraguay', 727, 'Omar Alderete',                      'player'),
('Paraguay', 728, 'Junior Alonso',                      'player'),
('Paraguay', 729, 'Mathías Villasanti',                 'player'),
('Paraguay', 730, 'Diego Gómez',                        'player'),
('Paraguay', 731, 'Damián Bobadilla',                   'player'),
('Paraguay', 732, 'Andrés Cubas',                       'player'),
('Paraguay', 733, 'Plantel Paraguay',                   'special'),
('Paraguay', 734, 'Matías Galarza Fonda',               'player'),
('Paraguay', 735, 'Julio Enciso',                       'player'),
('Paraguay', 736, 'Alejandro Romero Gamarra "Kaku"',    'player'),
('Paraguay', 737, 'Miguel Almirón',                     'player'),
('Paraguay', 738, 'Ramón Sosa',                         'player'),
('Paraguay', 739, 'Ángel Romero',                       'player'),
('Paraguay', 740, 'Antonio Sanabria',                   'player'),

-- =============================================
-- PORTUGAL — POR (741-760)
-- =============================================
('Portugal', 741, 'Escudo Portugal',          'badge'),
('Portugal', 742, 'Diogo Costa',              'player'),
('Portugal', 743, 'José Sá',                  'player'),
('Portugal', 744, 'Rúben Dias',               'player'),
('Portugal', 745, 'João Cancelo',             'player'),
('Portugal', 746, 'Diogo Dalot',              'player'),
('Portugal', 747, 'Nuno Mendes',              'player'),
('Portugal', 748, 'Gonçalo Inácio',           'player'),
('Portugal', 749, 'Bernardo Silva',           'player'),
('Portugal', 750, 'Bruno Fernandes',          'player'),
('Portugal', 751, 'Rúben Neves',              'player'),
('Portugal', 752, 'Vitinha',                  'player'),
('Portugal', 753, 'Plantel Portugal',         'special'),
('Portugal', 754, 'João Neves',               'player'),
('Portugal', 755, 'Cristiano Ronaldo',        'player'),
('Portugal', 756, 'Francisco Trincão',        'player'),
('Portugal', 757, 'João Félix',               'player'),
('Portugal', 758, 'Gonçalo Ramos',            'player'),
('Portugal', 759, 'Pedro Neto',               'player'),
('Portugal', 760, 'Rafael Leão',              'player'),

-- =============================================
-- QATAR — QAT (761-780)
-- =============================================
('Qatar', 761, 'Escudo Qatar',            'badge'),
('Qatar', 762, 'Meshaal Barsham',         'player'),
('Qatar', 763, 'Sultan Albrake',          'player'),
('Qatar', 764, 'Lucas Mendes',            'player'),
('Qatar', 765, 'Homam Ahmed',             'player'),
('Qatar', 766, 'Boualem Khoukhi',         'player'),
('Qatar', 767, 'Pedro Miguel',            'player'),
('Qatar', 768, 'Tarek Salman',            'player'),
('Qatar', 769, 'Mohamed Al-Mannai',       'player'),
('Qatar', 770, 'Karim Boudiaf',           'player'),
('Qatar', 771, 'Assim Madibo',            'player'),
('Qatar', 772, 'Ahmed Fatehi',            'player'),
('Qatar', 773, 'Plantel Qatar',           'special'),
('Qatar', 774, 'Mohammed Waad',           'player'),
('Qatar', 775, 'Abdulaziz Hatem',         'player'),
('Qatar', 776, 'Hassan Al-Haydos',        'player'),
('Qatar', 777, 'Edmilson Junior',         'player'),
('Qatar', 778, 'Akram Hassan Afif',       'player'),
('Qatar', 779, 'Ahmed Al Ganehi',         'player'),
('Qatar', 780, 'Almoez Ali',              'player'),

-- =============================================
-- SUDÁFRICA — RSA (781-800)
-- =============================================
('Sudáfrica', 781, 'Escudo Sudáfrica',      'badge'),
('Sudáfrica', 782, 'Ronwen Williams',       'player'),
('Sudáfrica', 783, 'Sipho Chaine',          'player'),
('Sudáfrica', 784, 'Aubrey Modiba',         'player'),
('Sudáfrica', 785, 'Samukele Kabini',       'player'),
('Sudáfrica', 786, 'Mbekezeli Mbokazi',     'player'),
('Sudáfrica', 787, 'Khulumani Ndamane',     'player'),
('Sudáfrica', 788, 'Siyabonga Ngezana',     'player'),
('Sudáfrica', 789, 'Khuliso Mudau',         'player'),
('Sudáfrica', 790, 'Nkosinathi Sibisi',     'player'),
('Sudáfrica', 791, 'Teboho Mokoena',        'player'),
('Sudáfrica', 792, 'Thalente Mbatha',       'player'),
('Sudáfrica', 793, 'Plantel Sudáfrica',     'special'),
('Sudáfrica', 794, 'Bathasi Aubaas',        'player'),
('Sudáfrica', 795, 'Yaya Sithole',          'player'),
('Sudáfrica', 796, 'Sipho Mbule',           'player'),
('Sudáfrica', 797, 'Lyle Foster',           'player'),
('Sudáfrica', 798, 'Iqraam Rayners',        'player'),
('Sudáfrica', 799, 'Mohau Nkota',           'player'),
('Sudáfrica', 800, 'Oswin Appollis',        'player'),

-- =============================================
-- ESCOCIA — SCO (801-820)
-- =============================================
('Escocia', 801, 'Escudo Escocia',        'badge'),
('Escocia', 802, 'Angus Gunn',            'player'),
('Escocia', 803, 'Jack Hendry',           'player'),
('Escocia', 804, 'Kieran Tierney',        'player'),
('Escocia', 805, 'Aaron Hickey',          'player'),
('Escocia', 806, 'Andrew Robertson',      'player'),
('Escocia', 807, 'Scott McKenna',         'player'),
('Escocia', 808, 'John Souttar',          'player'),
('Escocia', 809, 'Anthony Ralston',       'player'),
('Escocia', 810, 'Grant Hanley',          'player'),
('Escocia', 811, 'Scott McTominay',       'player'),
('Escocia', 812, 'Billy Gilmour',         'player'),
('Escocia', 813, 'Plantel Escocia',       'special'),
('Escocia', 814, 'Lewis Ferguson',        'player'),
('Escocia', 815, 'Ryan Christie',         'player'),
('Escocia', 816, 'Kenny McLean',          'player'),
('Escocia', 817, 'John McGinn',           'player'),
('Escocia', 818, 'Lyndon Dykes',          'player'),
('Escocia', 819, 'Che Adams',             'player'),
('Escocia', 820, 'Ben Doak',              'player'),

-- =============================================
-- SENEGAL — SEN (821-840)
-- =============================================
('Senegal', 821, 'Escudo Senegal',           'badge'),
('Senegal', 822, 'Edouard Mendy',            'player'),
('Senegal', 823, 'Yehvann Diouf',            'player'),
('Senegal', 824, 'Moussa Niakhaté',          'player'),
('Senegal', 825, 'Abdoulaye Seck',           'player'),
('Senegal', 826, 'Ismail Jakobs',            'player'),
('Senegal', 827, 'El Hadji Malick Diouf',    'player'),
('Senegal', 828, 'Kalidou Koulibaly',        'player'),
('Senegal', 829, 'Idrissa Gana Gueye',       'player'),
('Senegal', 830, 'Pape Matar Sarr',          'player'),
('Senegal', 831, 'Pape Gueye',               'player'),
('Senegal', 832, 'Habib Diarra',             'player'),
('Senegal', 833, 'Plantel Senegal',          'special'),
('Senegal', 834, 'Lamine Camara',            'player'),
('Senegal', 835, 'Sadio Mané',               'player'),
('Senegal', 836, 'Ismaïla Sarr',             'player'),
('Senegal', 837, 'Boulaye Dia',              'player'),
('Senegal', 838, 'Iliman Ndiaye',            'player'),
('Senegal', 839, 'Nicolas Jackson',          'player'),
('Senegal', 840, 'Krepin Diatta',            'player'),

-- =============================================
-- SUIZA — SUI (841-860)
-- =============================================
('Suiza', 841, 'Escudo Suiza',           'badge'),
('Suiza', 842, 'Gregor Kobel',           'player'),
('Suiza', 843, 'Yvon Mvogo',             'player'),
('Suiza', 844, 'Manuel Akanji',          'player'),
('Suiza', 845, 'Ricardo Rodríguez',      'player'),
('Suiza', 846, 'Nico Elvedi',            'player'),
('Suiza', 847, 'Aurèle Amenda',          'player'),
('Suiza', 848, 'Silvan Widmer',          'player'),
('Suiza', 849, 'Granit Xhaka',           'player'),
('Suiza', 850, 'Denis Zakaria',          'player'),
('Suiza', 851, 'Remo Freuler',           'player'),
('Suiza', 852, 'Fabian Rieder',          'player'),
('Suiza', 853, 'Plantel Suiza',          'special'),
('Suiza', 854, 'Ardon Jashari',          'player'),
('Suiza', 855, 'Johan Manzambi',         'player'),
('Suiza', 856, 'Michel Aebischer',       'player'),
('Suiza', 857, 'Breel Embolo',           'player'),
('Suiza', 858, 'Ruben Vargas',           'player'),
('Suiza', 859, 'Dan Ndoye',              'player'),
('Suiza', 860, 'Zeki Amdouni',           'player'),

-- =============================================
-- SUECIA — SWE (861-880)
-- =============================================
('Suecia', 861, 'Escudo Suecia',               'badge'),
('Suecia', 862, 'Victor Johansson',            'player'),
('Suecia', 863, 'Isak Hien',                   'player'),
('Suecia', 864, 'Gabriel Gudmundsson',         'player'),
('Suecia', 865, 'Emil Holm',                   'player'),
('Suecia', 866, 'Victor Nilsson Lindelöf',     'player'),
('Suecia', 867, 'Gustaf Lagerbielke',          'player'),
('Suecia', 868, 'Lucas Bergvall',              'player'),
('Suecia', 869, 'Hugo Larsson',                'player'),
('Suecia', 870, 'Jesper Karlström',            'player'),
('Suecia', 871, 'Yasin Ayari',                 'player'),
('Suecia', 872, 'Mattias Svanberg',            'player'),
('Suecia', 873, 'Plantel Suecia',              'special'),
('Suecia', 874, 'Daniel Svensson',             'player'),
('Suecia', 875, 'Ken Sema',                    'player'),
('Suecia', 876, 'Roony Bardghji',              'player'),
('Suecia', 877, 'Dejan Kulusevski',            'player'),
('Suecia', 878, 'Anthony Elanga',              'player'),
('Suecia', 879, 'Alexander Isak',              'player'),
('Suecia', 880, 'Viktor Gyökeres',             'player'),

-- =============================================
-- TÚNEZ — TUN (881-900)
-- =============================================
('Túnez', 881, 'Escudo Túnez',                    'badge'),
('Túnez', 882, 'Bechir Ben Said',                 'player'),
('Túnez', 883, 'Aymen Dahmen',                    'player'),
('Túnez', 884, 'Yan Valery',                      'player'),
('Túnez', 885, 'Montassar Talbi',                 'player'),
('Túnez', 886, 'Yassine Meriah',                  'player'),
('Túnez', 887, 'Ali Abdi',                        'player'),
('Túnez', 888, 'Dylan Bronn',                     'player'),
('Túnez', 889, 'Ellyes Skhiri',                   'player'),
('Túnez', 890, 'Aissa Laidouni',                  'player'),
('Túnez', 891, 'Ferjani Sassi',                   'player'),
('Túnez', 892, 'Mohamed Ali Ben Romdhane',         'player'),
('Túnez', 893, 'Plantel Túnez',                   'special'),
('Túnez', 894, 'Hannibal Mejbri',                 'player'),
('Túnez', 895, 'Elias Achouri',                   'player'),
('Túnez', 896, 'Elias Saad',                      'player'),
('Túnez', 897, 'Hazem Mastouri',                  'player'),
('Túnez', 898, 'Ismael Gharbi',                   'player'),
('Túnez', 899, 'Sayfallah Ltaief',                'player'),
('Túnez', 900, 'Naim Sliti',                      'player'),

-- =============================================
-- TURQUÍA — TUR (901-920)
-- =============================================
('Turquía', 901, 'Escudo Turquía',          'badge'),
('Turquía', 902, 'Uğurcan Çakır',           'player'),
('Turquía', 903, 'Mert Müldür',             'player'),
('Turquía', 904, 'Zeki Çelik',              'player'),
('Turquía', 905, 'Abdülkerim Bardakcı',     'player'),
('Turquía', 906, 'Çağlar Söyüncü',          'player'),
('Turquía', 907, 'Merih Demiral',           'player'),
('Turquía', 908, 'Ferdi Kadıoğlu',          'player'),
('Turquía', 909, 'Kaan Ayhan',              'player'),
('Turquía', 910, 'İsmail Yüksek',           'player'),
('Turquía', 911, 'Hakan Çalhanoğlu',        'player'),
('Turquía', 912, 'Orkun Kökçü',             'player'),
('Turquía', 913, 'Plantel Turquía',         'special'),
('Turquía', 914, 'Arda Güler',              'player'),
('Turquía', 915, 'İrfan Can Kahveci',       'player'),
('Turquía', 916, 'Yunus Akgün',             'player'),
('Turquía', 917, 'Can Uzun',                'player'),
('Turquía', 918, 'Barış Alper Yılmaz',      'player'),
('Turquía', 919, 'Kerem Aktürkoğlu',        'player'),
('Turquía', 920, 'Kenan Yıldız',            'player'),

-- =============================================
-- URUGUAY — URU (921-940)
-- =============================================
('Uruguay', 921, 'Escudo Uruguay',              'badge'),
('Uruguay', 922, 'Sergio Rochet',               'player'),
('Uruguay', 923, 'Santiago Mele',               'player'),
('Uruguay', 924, 'Ronald Araújo',               'player'),
('Uruguay', 925, 'José María Giménez',          'player'),
('Uruguay', 926, 'Sebastián Cáceres',           'player'),
('Uruguay', 927, 'Mathías Olivera',             'player'),
('Uruguay', 928, 'Guillermo Varela',            'player'),
('Uruguay', 929, 'Nahitán Nández',              'player'),
('Uruguay', 930, 'Federico Valverde',           'player'),
('Uruguay', 931, 'Giorgian De Arrascaeta',      'player'),
('Uruguay', 932, 'Rodrigo Bentancur',           'player'),
('Uruguay', 933, 'Plantel Uruguay',             'special'),
('Uruguay', 934, 'Manuel Ugarte',               'player'),
('Uruguay', 935, 'Nicolás de la Cruz',          'player'),
('Uruguay', 936, 'Maximiliano Araújo',          'player'),
('Uruguay', 937, 'Darwin Núñez',                'player'),
('Uruguay', 938, 'Federico Viñas',              'player'),
('Uruguay', 939, 'Rodrigo Aguirre',             'player'),
('Uruguay', 940, 'Facundo Pellistri',           'player'),

-- =============================================
-- ESTADOS UNIDOS — USA (941-960)
-- =============================================
('Estados Unidos', 941, 'Escudo Estados Unidos',   'badge'),
('Estados Unidos', 942, 'Matt Freese',             'player'),
('Estados Unidos', 943, 'Chris Richards',          'player'),
('Estados Unidos', 944, 'Tim Ream',                'player'),
('Estados Unidos', 945, 'Mark McKenzie',           'player'),
('Estados Unidos', 946, 'Alex Freeman',            'player'),
('Estados Unidos', 947, 'Antonee Robinson',        'player'),
('Estados Unidos', 948, 'Tyler Adams',             'player'),
('Estados Unidos', 949, 'Tanner Tessmann',         'player'),
('Estados Unidos', 950, 'Weston McKennie',         'player'),
('Estados Unidos', 951, 'Christian Roldan',        'player'),
('Estados Unidos', 952, 'Timothy Weah',            'player'),
('Estados Unidos', 953, 'Plantel Estados Unidos',  'special'),
('Estados Unidos', 954, 'Diego Luna',              'player'),
('Estados Unidos', 955, 'Malik Tillman',           'player'),
('Estados Unidos', 956, 'Christian Pulisic',       'player'),
('Estados Unidos', 957, 'Brenden Aaronson',        'player'),
('Estados Unidos', 958, 'Ricardo Pepi',            'player'),
('Estados Unidos', 959, 'Haji Wright',             'player'),
('Estados Unidos', 960, 'Folarin Balogun',         'player'),

-- =============================================
-- UZBEKISTÁN — UZB (961-980)
-- =============================================
('Uzbekistán', 961, 'Escudo Uzbekistán',         'badge'),
('Uzbekistán', 962, 'Utkir Yusupov',             'player'),
('Uzbekistán', 963, 'Farrukh Sayfiev',           'player'),
('Uzbekistán', 964, 'Sherzod Nasrullaev',        'player'),
('Uzbekistán', 965, 'Umar Eshmurodov',           'player'),
('Uzbekistán', 966, 'Husniddin Aliqulov',        'player'),
('Uzbekistán', 967, 'Rustamjon Ashurmatov',      'player'),
('Uzbekistán', 968, 'Khojiakbar Alijonov',       'player'),
('Uzbekistán', 969, 'Abdukodir Khusanov',        'player'),
('Uzbekistán', 970, 'Odiljon Hamrobekov',        'player'),
('Uzbekistán', 971, 'Otabek Shukurov',           'player'),
('Uzbekistán', 972, 'Jamshid Iskanderov',        'player'),
('Uzbekistán', 973, 'Plantel Uzbekistán',        'special'),
('Uzbekistán', 974, 'Azizbek Turgunboev',        'player'),
('Uzbekistán', 975, 'Khojimat Erkinov',          'player'),
('Uzbekistán', 976, 'Eldor Shomurodov',          'player'),
('Uzbekistán', 977, 'Oston Urunov',              'player'),
('Uzbekistán', 978, 'Jaloliddin Masharipov',     'player'),
('Uzbekistán', 979, 'Igor Sergeev',              'player'),
('Uzbekistán', 980, 'Abbosbek Fayzullaev',       'player');
