-- =============================================
-- Panini FIFA World Cup 2026 — Catálogo completo
-- 48 equipos × 20 láminas + 20 intro = 980 láminas
-- Ejecutar DESPUÉS de schema.sql
-- =============================================

TRUNCATE TABLE public.user_stickers;
TRUNCATE TABLE public.stickers RESTART IDENTITY CASCADE;

INSERT INTO public.stickers (section, number, name, type) VALUES

-- =============================================
-- INTRODUCCIÓN (1-20)
-- =============================================
('Introducción', 1,  'Portada del Álbum',              'special'),
('Introducción', 2,  'Trofeo Copa del Mundo FIFA',      'special'),
('Introducción', 3,  'Mascota Oficial "Taíno"',         'special'),
('Introducción', 4,  'Emblema Oficial WC2026',          'special'),
('Introducción', 5,  'Balón Oficial',                   'special'),
('Introducción', 6,  'Sede: Estados Unidos',            'special'),
('Introducción', 7,  'Sede: Canadá',                    'special'),
('Introducción', 8,  'Sede: México',                    'special'),
('Introducción', 9,  'MetLife Stadium — Nueva York',    'stadium'),
('Introducción', 10, 'AT&T Stadium — Dallas',           'stadium'),
('Introducción', 11, 'SoFi Stadium — Los Ángeles',      'stadium'),
('Introducción', 12, 'Hard Rock Stadium — Miami',       'stadium'),
('Introducción', 13, 'Levi\'s Stadium — San Francisco', 'stadium'),
('Introducción', 14, 'Arrowhead Stadium — Kansas City', 'stadium'),
('Introducción', 15, 'Lincoln Financial Field — Phila.','stadium'),
('Introducción', 16, 'BC Place — Vancouver',            'stadium'),
('Introducción', 17, 'Estadio Azteca — Ciudad de Méx.', 'stadium'),
('Introducción', 18, 'Estadio Akron — Guadalajara',     'stadium'),
('Introducción', 19, 'Estadio BBVA — Monterrey',        'stadium'),
('Introducción', 20, 'Campeones del Mundo — Historia',  'special'),

-- =============================================
-- ALEMANIA (21-40)
-- =============================================
('Alemania', 21, 'Escudo Alemania',        'badge'),
('Alemania', 22, 'Plantel Alemania',       'special'),
('Alemania', 23, 'Manuel Neuer',           'player'),
('Alemania', 24, 'Marc-André ter Stegen',  'player'),
('Alemania', 25, 'Toni Rüdiger',           'player'),
('Alemania', 26, 'Jonathan Tah',           'player'),
('Alemania', 27, 'Joshua Kimmich',         'player'),
('Alemania', 28, 'Ilkay Gündogan',         'player'),
('Alemania', 29, 'Leon Goretzka',          'player'),
('Alemania', 30, 'Florian Wirtz',          'player'),
('Alemania', 31, 'Jamal Musiala',          'player'),
('Alemania', 32, 'Leroy Sané',             'player'),
('Alemania', 33, 'Kai Havertz',            'player'),
('Alemania', 34, 'Niclas Füllkrug',        'player'),
('Alemania', 35, 'Thomas Müller',          'player'),
('Alemania', 36, 'David Raum',             'player'),
('Alemania', 37, 'Robert Andrich',         'player'),
('Alemania', 38, 'Deniz Undav',            'player'),
('Alemania', 39, 'Chris Führich',          'player'),
('Alemania', 40, 'Maximilian Mittelstädt', 'player'),

-- =============================================
-- ALGERIA (41-60)
-- =============================================
('Algeria', 41, 'Escudo Algeria',       'badge'),
('Algeria', 42, 'Plantel Algeria',      'special'),
('Algeria', 43, 'Raïs M''Bolhi',        'player'),
('Algeria', 44, 'Riyad Mahrez',         'player'),
('Algeria', 45, 'Ismail Bennacer',      'player'),
('Algeria', 46, 'Youcef Atal',          'player'),
('Algeria', 47, 'Ramy Bensebaïni',      'player'),
('Algeria', 48, 'Said Benrahma',        'player'),
('Algeria', 49, 'Farès Chaïbi',         'player'),
('Algeria', 50, 'Mohamed Amoura',       'player'),
('Algeria', 51, 'Hichem Boudaoui',      'player'),
('Algeria', 52, 'Djamel Benlamri',      'player'),
('Algeria', 53, 'Aïssa Mandi',          'player'),
('Algeria', 54, 'Yacine Brahimi',       'player'),
('Algeria', 55, 'Baghdad Bounedjah',    'player'),
('Algeria', 56, 'Zakaria Aboukhlal',    'player'),
('Algeria', 57, 'Andy Delort',          'player'),
('Algeria', 58, 'Adam Ounas',           'player'),
('Algeria', 59, 'Ryad Boudebouz',       'player'),
('Algeria', 60, 'Islam Slimani',        'player'),

-- =============================================
-- ARABIA SAUDITA (61-80)
-- =============================================
('Arabia Saudita', 61, 'Escudo Arabia Saudita',  'badge'),
('Arabia Saudita', 62, 'Plantel Arabia Saudita', 'special'),
('Arabia Saudita', 63, 'Mohammed Al-Owais',      'player'),
('Arabia Saudita', 64, 'Salem Al-Dawsari',       'player'),
('Arabia Saudita', 65, 'Mohammed Al-Burayk',     'player'),
('Arabia Saudita', 66, 'Ali Al-Bulaihi',         'player'),
('Arabia Saudita', 67, 'Abdulelah Al-Malki',     'player'),
('Arabia Saudita', 68, 'Firas Al-Buraikan',      'player'),
('Arabia Saudita', 69, 'Saleh Al-Shehri',        'player'),
('Arabia Saudita', 70, 'Yasir Al-Shahrani',      'player'),
('Arabia Saudita', 71, 'Abdullah Al-Hamdan',     'player'),
('Arabia Saudita', 72, 'Hassan Al-Tambakti',     'player'),
('Arabia Saudita', 73, 'Mohammed Kanno',         'player'),
('Arabia Saudita', 74, 'Sami Al-Najei',          'player'),
('Arabia Saudita', 75, 'Sultan Al-Ghannam',      'player'),
('Arabia Saudita', 76, 'Ahmed Sharahili',        'player'),
('Arabia Saudita', 77, 'Nawaf Al-Aqidi',         'player'),
('Arabia Saudita', 78, 'Ali Al-Hassan',          'player'),
('Arabia Saudita', 79, 'Riyadh Sharahili',       'player'),
('Arabia Saudita', 80, 'Nasser Al-Dawsari',      'player'),

-- =============================================
-- ARGENTINA (81-100)
-- =============================================
('Argentina', 81,  'Escudo Argentina',       'badge'),
('Argentina', 82,  'Plantel Argentina',      'special'),
('Argentina', 83,  'Emiliano Martínez',      'player'),
('Argentina', 84,  'Nahuel Molina',          'player'),
('Argentina', 85,  'Nicolás Otamendi',       'player'),
('Argentina', 86,  'Lisandro Martínez',      'player'),
('Argentina', 87,  'Nicolás Tagliafico',     'player'),
('Argentina', 88,  'Rodrigo De Paul',        'player'),
('Argentina', 89,  'Leandro Paredes',        'player'),
('Argentina', 90,  'Alexis Mac Allister',    'player'),
('Argentina', 91,  'Enzo Fernández',         'player'),
('Argentina', 92,  'Lionel Messi',           'player'),
('Argentina', 93,  'Ángel Di María',         'player'),
('Argentina', 94,  'Lautaro Martínez',       'player'),
('Argentina', 95,  'Julián Álvarez',         'player'),
('Argentina', 96,  'Paulo Dybala',           'player'),
('Argentina', 97,  'Alejandro Garnacho',     'player'),
('Argentina', 98,  'Germán Pezzella',        'player'),
('Argentina', 99,  'Thiago Almada',          'player'),
('Argentina', 100, 'Valentín Carboni',       'player'),

-- =============================================
-- AUSTRALIA (101-120)
-- =============================================
('Australia', 101, 'Escudo Australia',    'badge'),
('Australia', 102, 'Plantel Australia',   'special'),
('Australia', 103, 'Mathew Ryan',         'player'),
('Australia', 104, 'Mat Leckie',          'player'),
('Australia', 105, 'Harry Souttar',       'player'),
('Australia', 106, 'Bailey Wright',       'player'),
('Australia', 107, 'Aziz Behich',         'player'),
('Australia', 108, 'Jackson Irvine',      'player'),
('Australia', 109, 'Aaron Mooy',          'player'),
('Australia', 110, 'Riley McGree',        'player'),
('Australia', 111, 'Martin Boyle',        'player'),
('Australia', 112, 'Mitchell Duke',       'player'),
('Australia', 113, 'Jamie Maclaren',      'player'),
('Australia', 114, 'Garang Kuol',         'player'),
('Australia', 115, 'Nathaniel Atkinson',  'player'),
('Australia', 116, 'Keanu Baccus',        'player'),
('Australia', 117, 'Kye Rowles',          'player'),
('Australia', 118, 'Cameron Devlin',      'player'),
('Australia', 119, 'Denis Genreau',       'player'),
('Australia', 120, 'Jordan Bos',          'player'),

-- =============================================
-- AUSTRIA (121-140)
-- =============================================
('Austria', 121, 'Escudo Austria',          'badge'),
('Austria', 122, 'Plantel Austria',         'special'),
('Austria', 123, 'Patrick Pentz',           'player'),
('Austria', 124, 'David Alaba',             'player'),
('Austria', 125, 'Marcel Sabitzer',         'player'),
('Austria', 126, 'Konrad Laimer',           'player'),
('Austria', 127, 'Christoph Baumgartner',   'player'),
('Austria', 128, 'Nicolas Seiwald',         'player'),
('Austria', 129, 'Michael Gregoritsch',     'player'),
('Austria', 130, 'Marko Arnautović',        'player'),
('Austria', 131, 'Kevin Danso',             'player'),
('Austria', 132, 'Philipp Lienhart',        'player'),
('Austria', 133, 'Stefan Posch',            'player'),
('Austria', 134, 'Maximilian Wöber',        'player'),
('Austria', 135, 'Romano Schmid',           'player'),
('Austria', 136, 'Patrick Wimmer',          'player'),
('Austria', 137, 'Florian Grillitsch',      'player'),
('Austria', 138, 'Sasa Kalajdzic',          'player'),
('Austria', 139, 'Dejan Ljubičić',          'player'),
('Austria', 140, 'Mwene Philipp',           'player'),

-- =============================================
-- BÉLGICA (141-160)
-- =============================================
('Bélgica', 141, 'Escudo Bélgica',       'badge'),
('Bélgica', 142, 'Plantel Bélgica',      'special'),
('Bélgica', 143, 'Thibaut Courtois',     'player'),
('Bélgica', 144, 'Koen Casteels',        'player'),
('Bélgica', 145, 'Timothy Castagne',     'player'),
('Bélgica', 146, 'Arthur Theate',        'player'),
('Bélgica', 147, 'Wout Faes',            'player'),
('Bélgica', 148, 'Kevin De Bruyne',      'player'),
('Bélgica', 149, 'Amadou Onana',         'player'),
('Bélgica', 150, 'Yannick Carrasco',     'player'),
('Bélgica', 151, 'Jeremy Doku',          'player'),
('Bélgica', 152, 'Lois Openda',          'player'),
('Bélgica', 153, 'Romelu Lukaku',        'player'),
('Bélgica', 154, 'Leandro Trossard',     'player'),
('Bélgica', 155, 'Charles De Ketelaere', 'player'),
('Bélgica', 156, 'Johan Bakayoko',       'player'),
('Bélgica', 157, 'Axel Witsel',          'player'),
('Bélgica', 158, 'Jan Vertonghen',       'player'),
('Bélgica', 159, 'Alexis Saelemaekers', 'player'),
('Bélgica', 160, 'Dries Mertens',        'player'),

-- =============================================
-- BRASIL (161-180)
-- =============================================
('Brasil', 161, 'Escudo Brasil',        'badge'),
('Brasil', 162, 'Plantel Brasil',       'special'),
('Brasil', 163, 'Alisson Becker',       'player'),
('Brasil', 164, 'Ederson',              'player'),
('Brasil', 165, 'Danilo',               'player'),
('Brasil', 166, 'Éder Militão',         'player'),
('Brasil', 167, 'Marquinhos',           'player'),
('Brasil', 168, 'Gabriel Magalhães',    'player'),
('Brasil', 169, 'Guilherme Arana',      'player'),
('Brasil', 170, 'Casemiro',             'player'),
('Brasil', 171, 'Bruno Guimarães',      'player'),
('Brasil', 172, 'Lucas Paquetá',        'player'),
('Brasil', 173, 'Rodrygo',              'player'),
('Brasil', 174, 'Raphinha',             'player'),
('Brasil', 175, 'Vinicius Jr.',         'player'),
('Brasil', 176, 'Endrick',              'player'),
('Brasil', 177, 'Savinho',              'player'),
('Brasil', 178, 'Estêvão',              'player'),
('Brasil', 179, 'Gabriel Martinelli',   'player'),
('Brasil', 180, 'Gerson',               'player'),

-- =============================================
-- CAMERÚN (181-200)
-- =============================================
('Camerún', 181, 'Escudo Camerún',              'badge'),
('Camerún', 182, 'Plantel Camerún',             'special'),
('Camerún', 183, 'André Onana',                 'player'),
('Camerún', 184, 'Vincent Aboubakar',           'player'),
('Camerún', 185, 'Karl Toko-Ekambi',            'player'),
('Camerún', 186, 'Nicolas Ngamaleu',            'player'),
('Camerún', 187, 'Jean-Charles Castelletto',    'player'),
('Camerún', 188, 'Michael Ngadeu-Ngadjui',      'player'),
('Camerún', 189, 'Collins Fai',                 'player'),
('Camerún', 190, 'Nouhou Tolo',                 'player'),
('Camerún', 191, 'Olivier Ntcham',              'player'),
('Camerún', 192, 'Martin Hongla',               'player'),
('Camerún', 193, 'Gaël Ondoua',                 'player'),
('Camerún', 194, 'Christian Bassogog',          'player'),
('Camerún', 195, 'Samuel Gouet',                'player'),
('Camerún', 196, 'Harold Moukoudi',             'player'),
('Camerún', 197, 'Stéphane Bahoken',            'player'),
('Camerún', 198, 'Jerome Onguene',              'player'),
('Camerún', 199, 'Léandre Tawamba',             'player'),
('Camerún', 200, 'Frank Magri',                 'player'),

-- =============================================
-- CANADÁ (201-220)
-- =============================================
('Canadá', 201, 'Escudo Canadá',         'badge'),
('Canadá', 202, 'Plantel Canadá',        'special'),
('Canadá', 203, 'Maxime Crépeau',        'player'),
('Canadá', 204, 'Milan Borjan',          'player'),
('Canadá', 205, 'Alphonso Davies',       'player'),
('Canadá', 206, 'Alistair Johnston',     'player'),
('Canadá', 207, 'Kamal Miller',          'player'),
('Canadá', 208, 'Derek Cornelius',       'player'),
('Canadá', 209, 'Richie Laryea',         'player'),
('Canadá', 210, 'Stephen Eustáquio',     'player'),
('Canadá', 211, 'Ismaël Koné',           'player'),
('Canadá', 212, 'Jonathan David',        'player'),
('Canadá', 213, 'Tajon Buchanan',        'player'),
('Canadá', 214, 'Cyle Larin',            'player'),
('Canadá', 215, 'Liam Millar',           'player'),
('Canadá', 216, 'Samuel Piette',         'player'),
('Canadá', 217, 'Mathieu Choinière',     'player'),
('Canadá', 218, 'Atiba Hutchinson',      'player'),
('Canadá', 219, 'Lucas Cavallini',       'player'),
('Canadá', 220, 'Ali Ahmed',             'player'),

-- =============================================
-- CHEQUIA (221-240)
-- =============================================
('Chequia', 221, 'Escudo Chequia',          'badge'),
('Chequia', 222, 'Plantel Chequia',         'special'),
('Chequia', 223, 'Jiří Staněk',             'player'),
('Chequia', 224, 'Tomáš Vaclík',            'player'),
('Chequia', 225, 'Vladimír Coufal',         'player'),
('Chequia', 226, 'Tomáš Souček',            'player'),
('Chequia', 227, 'Patrik Schick',           'player'),
('Chequia', 228, 'Ondřej Duda',             'player'),
('Chequia', 229, 'Antonín Barák',           'player'),
('Chequia', 230, 'Ladislav Krejčí',         'player'),
('Chequia', 231, 'Tomáš Holeš',             'player'),
('Chequia', 232, 'David Jurásek',           'player'),
('Chequia', 233, 'Jakub Jankto',            'player'),
('Chequia', 234, 'Lukáš Provod',            'player'),
('Chequia', 235, 'Jan Kuchta',              'player'),
('Chequia', 236, 'Adam Hložek',             'player'),
('Chequia', 237, 'Matěj Jurásek',           'player'),
('Chequia', 238, 'Alex Král',               'player'),
('Chequia', 239, 'Lukáš Červíček',          'player'),
('Chequia', 240, 'Pavel Šulc',              'player'),

-- =============================================
-- COLOMBIA (241-260)
-- =============================================
('Colombia', 241, 'Escudo Colombia',       'badge'),
('Colombia', 242, 'Plantel Colombia',      'special'),
('Colombia', 243, 'Camilo Vargas',         'player'),
('Colombia', 244, 'Daniel Muñoz',          'player'),
('Colombia', 245, 'Dávinson Sánchez',      'player'),
('Colombia', 246, 'Yerry Mina',            'player'),
('Colombia', 247, 'Johan Mojica',          'player'),
('Colombia', 248, 'Wilmar Barrios',        'player'),
('Colombia', 249, 'Mateus Uribe',          'player'),
('Colombia', 250, 'Richard Ríos',          'player'),
('Colombia', 251, 'James Rodríguez',       'player'),
('Colombia', 252, 'Luis Díaz',             'player'),
('Colombia', 253, 'Jhon Córdoba',          'player'),
('Colombia', 254, 'Rafael Santos Borré',   'player'),
('Colombia', 255, 'Cucho Hernández',       'player'),
('Colombia', 256, 'Jhon Durán',            'player'),
('Colombia', 257, 'Juan Guillermo Cuadrado','player'),
('Colombia', 258, 'Sebastián Villa',       'player'),
('Colombia', 259, 'Jorge Carrascal',       'player'),
('Colombia', 260, 'Juan Fernando Quintero','player'),

-- =============================================
-- COREA DEL SUR (261-280)
-- =============================================
('Corea del Sur', 261, 'Escudo Corea del Sur',  'badge'),
('Corea del Sur', 262, 'Plantel Corea del Sur', 'special'),
('Corea del Sur', 263, 'Kim Seung-gyu',         'player'),
('Corea del Sur', 264, 'Son Heung-min',         'player'),
('Corea del Sur', 265, 'Kim Min-jae',           'player'),
('Corea del Sur', 266, 'Lee Kang-in',           'player'),
('Corea del Sur', 267, 'Hwang Hee-chan',         'player'),
('Corea del Sur', 268, 'Hwang In-beom',         'player'),
('Corea del Sur', 269, 'Cho Gue-sung',          'player'),
('Corea del Sur', 270, 'Lee Jae-sung',          'player'),
('Corea del Sur', 271, 'Kim Jin-su',            'player'),
('Corea del Sur', 272, 'Jeong Woo-yeong',       'player'),
('Corea del Sur', 273, 'Oh Hyeon-gyu',          'player'),
('Corea del Sur', 274, 'Paik Seung-ho',         'player'),
('Corea del Sur', 275, 'Na Sang-ho',            'player'),
('Corea del Sur', 276, 'Kim Young-gwon',        'player'),
('Corea del Sur', 277, 'Kwon Chang-hoon',       'player'),
('Corea del Sur', 278, 'Lee Yong',              'player'),
('Corea del Sur', 279, 'Park Hyun-bin',         'player'),
('Corea del Sur', 280, 'Song Min-kyu',          'player'),

-- =============================================
-- COSTA DE MARFIL (281-300)
-- =============================================
('Costa de Marfil', 281, 'Escudo Costa de Marfil',  'badge'),
('Costa de Marfil', 282, 'Plantel Costa de Marfil', 'special'),
('Costa de Marfil', 283, 'Yahia Fofana',            'player'),
('Costa de Marfil', 284, 'Serge Aurier',            'player'),
('Costa de Marfil', 285, 'Odilon Kossounou',        'player'),
('Costa de Marfil', 286, 'Willy Boly',              'player'),
('Costa de Marfil', 287, 'Ghislain Konan',          'player'),
('Costa de Marfil', 288, 'Franck Kessié',           'player'),
('Costa de Marfil', 289, 'Ibrahim Sangaré',         'player'),
('Costa de Marfil', 290, 'Seko Fofana',             'player'),
('Costa de Marfil', 291, 'Sebastien Haller',        'player'),
('Costa de Marfil', 292, 'Simon Adingra',           'player'),
('Costa de Marfil', 293, 'Nicolas Pépé',            'player'),
('Costa de Marfil', 294, 'Jean-Philippe Krasso',    'player'),
('Costa de Marfil', 295, 'Karim Konaté',            'player'),
('Costa de Marfil', 296, 'Silas Katompa',           'player'),
('Costa de Marfil', 297, 'Wilfried Zaha',           'player'),
('Costa de Marfil', 298, 'Steeve Yago',             'player'),
('Costa de Marfil', 299, 'Oumar Diakité',           'player'),
('Costa de Marfil', 300, 'Max-Alain Gradel',        'player'),

-- =============================================
-- CROACIA (301-320)
-- =============================================
('Croacia', 301, 'Escudo Croacia',         'badge'),
('Croacia', 302, 'Plantel Croacia',        'special'),
('Croacia', 303, 'Dominik Livaković',      'player'),
('Croacia', 304, 'Joško Gvardiol',         'player'),
('Croacia', 305, 'Dejan Lovren',           'player'),
('Croacia', 306, 'Martin Erlić',           'player'),
('Croacia', 307, 'Borna Sosa',             'player'),
('Croacia', 308, 'Luka Modrić',            'player'),
('Croacia', 309, 'Mateo Kovačić',          'player'),
('Croacia', 310, 'Marcelo Brozović',       'player'),
('Croacia', 311, 'Mario Pašalić',          'player'),
('Croacia', 312, 'Ivan Perišić',           'player'),
('Croacia', 313, 'Andrej Kramarić',        'player'),
('Croacia', 314, 'Ante Budimir',           'player'),
('Croacia', 315, 'Nikola Vlašić',          'player'),
('Croacia', 316, 'Bruno Petković',         'player'),
('Croacia', 317, 'Luka Sučić',             'player'),
('Croacia', 318, 'Šime Vrsaljko',          'player'),
('Croacia', 319, 'Dario Šimić',            'player'),
('Croacia', 320, 'Petar Sucić',            'player'),

-- =============================================
-- ECUADOR (321-340)
-- =============================================
('Ecuador', 321, 'Escudo Ecuador',        'badge'),
('Ecuador', 322, 'Plantel Ecuador',       'special'),
('Ecuador', 323, 'Alexander Domínguez',   'player'),
('Ecuador', 324, 'Piero Hincapié',        'player'),
('Ecuador', 325, 'Félix Torres',          'player'),
('Ecuador', 326, 'Diego Palacios',        'player'),
('Ecuador', 327, 'Angelo Preciado',       'player'),
('Ecuador', 328, 'Carlos Gruezo',         'player'),
('Ecuador', 329, 'Moisés Caicedo',        'player'),
('Ecuador', 330, 'Jeremy Sarmiento',      'player'),
('Ecuador', 331, 'Gonzalo Plata',         'player'),
('Ecuador', 332, 'Enner Valencia',        'player'),
('Ecuador', 333, 'Michael Estrada',       'player'),
('Ecuador', 334, 'John Yeboah',           'player'),
('Ecuador', 335, 'Pervis Estupiñán',      'player'),
('Ecuador', 336, 'Alan Minda',            'player'),
('Ecuador', 337, 'Ayrton Preciado',       'player'),
('Ecuador', 338, 'Byron Castillo',        'player'),
('Ecuador', 339, 'Ángel Mena',            'player'),
('Ecuador', 340, 'Djorkaeff Reasco',      'player'),

-- =============================================
-- EGIPTO (341-360)
-- =============================================
('Egipto', 341, 'Escudo Egipto',          'badge'),
('Egipto', 342, 'Plantel Egipto',         'special'),
('Egipto', 343, 'Mohamed El-Shenawy',     'player'),
('Egipto', 344, 'Gabaski',                'player'),
('Egipto', 345, 'Mohamed Salah',          'player'),
('Egipto', 346, 'Omar Marmoush',          'player'),
('Egipto', 347, 'Mostafa Mohamed',        'player'),
('Egipto', 348, 'Tarek Hamed',            'player'),
('Egipto', 349, 'Ahmed El-Sharkawy',      'player'),
('Egipto', 350, 'Ahmed Hegazi',           'player'),
('Egipto', 351, 'Mahmoud Hamada',         'player'),
('Egipto', 352, 'Ahmed Sayed "Zizou"',    'player'),
('Egipto', 353, 'Marawan Attia',          'player'),
('Egipto', 354, 'Hamdy Fathi',            'player'),
('Egipto', 355, 'Emam Ashour',            'player'),
('Egipto', 356, 'Akram Tawfik',           'player'),
('Egipto', 357, 'Mahmoud Afsha',          'player'),
('Egipto', 358, 'Mohamed Abdelmonem',     'player'),
('Egipto', 359, 'Ibrahim Adel',           'player'),
('Egipto', 360, 'Trézéguet',              'player'),

-- =============================================
-- ESPAÑA (361-380)
-- =============================================
('España', 361, 'Escudo España',          'badge'),
('España', 362, 'Plantel España',         'special'),
('España', 363, 'Unai Simón',             'player'),
('España', 364, 'David Raya',             'player'),
('España', 365, 'Dani Carvajal',          'player'),
('España', 366, 'Aymeric Laporte',        'player'),
('España', 367, 'Robin Le Normand',       'player'),
('España', 368, 'Alejandro Grimaldo',     'player'),
('España', 369, 'Rodri',                  'player'),
('España', 370, 'Pedri',                  'player'),
('España', 371, 'Fabián Ruiz',            'player'),
('España', 372, 'Gavi',                   'player'),
('España', 373, 'Lamine Yamal',           'player'),
('España', 374, 'Nico Williams',          'player'),
('España', 375, 'Álvaro Morata',          'player'),
('España', 376, 'Dani Olmo',              'player'),
('España', 377, 'Ferran Torres',          'player'),
('España', 378, 'Mikel Merino',           'player'),
('España', 379, 'Bryan Zaragoza',         'player'),
('España', 380, 'Joselu',                 'player'),

-- =============================================
-- ESCOCIA (381-400)
-- =============================================
('Escocia', 381, 'Escudo Escocia',       'badge'),
('Escocia', 382, 'Plantel Escocia',      'special'),
('Escocia', 383, 'Angus Gunn',           'player'),
('Escocia', 384, 'Craig Gordon',         'player'),
('Escocia', 385, 'Andrew Robertson',     'player'),
('Escocia', 386, 'Kieran Tierney',       'player'),
('Escocia', 387, 'Grant Hanley',         'player'),
('Escocia', 388, 'Scott McKenna',        'player'),
('Escocia', 389, 'Nathan Patterson',     'player'),
('Escocia', 390, 'Scott McTominay',      'player'),
('Escocia', 391, 'Callum McGregor',      'player'),
('Escocia', 392, 'John McGinn',          'player'),
('Escocia', 393, 'Billy Gilmour',        'player'),
('Escocia', 394, 'Ryan Christie',        'player'),
('Escocia', 395, 'Lawrence Shankland',   'player'),
('Escocia', 396, 'Che Adams',            'player'),
('Escocia', 397, 'Ben Doak',             'player'),
('Escocia', 398, 'Stuart Armstrong',     'player'),
('Escocia', 399, 'Kenny McLean',         'player'),
('Escocia', 400, 'Ross McCrorie',        'player'),

-- =============================================
-- ESTADOS UNIDOS (401-420)
-- =============================================
('Estados Unidos', 401, 'Escudo Estados Unidos',  'badge'),
('Estados Unidos', 402, 'Plantel Estados Unidos', 'special'),
('Estados Unidos', 403, 'Matt Turner',            'player'),
('Estados Unidos', 404, 'Zack Steffen',           'player'),
('Estados Unidos', 405, 'Sergiño Dest',           'player'),
('Estados Unidos', 406, 'Antonee Robinson',       'player'),
('Estados Unidos', 407, 'Chris Richards',         'player'),
('Estados Unidos', 408, 'Tim Ream',               'player'),
('Estados Unidos', 409, 'Tyler Adams',            'player'),
('Estados Unidos', 410, 'Weston McKennie',        'player'),
('Estados Unidos', 411, 'Yunus Musah',            'player'),
('Estados Unidos', 412, 'Christian Pulisic',      'player'),
('Estados Unidos', 413, 'Gio Reyna',              'player'),
('Estados Unidos', 414, 'Brenden Aaronson',       'player'),
('Estados Unidos', 415, 'Josh Sargent',           'player'),
('Estados Unidos', 416, 'Ricardo Pepi',           'player'),
('Estados Unidos', 417, 'Folarin Balogun',        'player'),
('Estados Unidos', 418, 'Malik Tillman',          'player'),
('Estados Unidos', 419, 'Jordan Morris',          'player'),
('Estados Unidos', 420, 'Cameron Carter-Vickers', 'player'),

-- =============================================
-- FRANCIA (421-440)
-- =============================================
('Francia', 421, 'Escudo Francia',          'badge'),
('Francia', 422, 'Plantel Francia',         'special'),
('Francia', 423, 'Mike Maignan',            'player'),
('Francia', 424, 'Alphonse Aréola',         'player'),
('Francia', 425, 'Benjamin Pavard',         'player'),
('Francia', 426, 'William Saliba',          'player'),
('Francia', 427, 'Ibrahima Konaté',         'player'),
('Francia', 428, 'Théo Hernández',          'player'),
('Francia', 429, 'Aurélien Tchouaméni',     'player'),
('Francia', 430, 'Adrien Rabiot',           'player'),
('Francia', 431, 'Eduardo Camavinga',       'player'),
('Francia', 432, 'Kylian Mbappé',           'player'),
('Francia', 433, 'Antoine Griezmann',       'player'),
('Francia', 434, 'Ousmane Dembélé',         'player'),
('Francia', 435, 'Marcus Thuram',           'player'),
('Francia', 436, 'Randal Kolo Muani',       'player'),
('Francia', 437, 'Bradley Barcola',         'player'),
('Francia', 438, 'Christopher Nkunku',      'player'),
('Francia', 439, 'Kingsley Coman',          'player'),
('Francia', 440, 'Raphaël Varane',          'player'),

-- =============================================
-- GHANA (441-460)
-- =============================================
('Ghana', 441, 'Escudo Ghana',             'badge'),
('Ghana', 442, 'Plantel Ghana',            'special'),
('Ghana', 443, 'Lawrence Ati-Zigi',        'player'),
('Ghana', 444, 'Thomas Partey',            'player'),
('Ghana', 445, 'Mohamed Kudus',            'player'),
('Ghana', 446, 'Iñaki Williams',           'player'),
('Ghana', 447, 'Jordan Ayew',              'player'),
('Ghana', 448, 'Tariq Lamptey',            'player'),
('Ghana', 449, 'Abdul-Rahman Baba',        'player'),
('Ghana', 450, 'Daniel Amartey',           'player'),
('Ghana', 451, 'Jonathon Mensah',          'player'),
('Ghana', 452, 'Alidu Seidu',              'player'),
('Ghana', 453, 'Ernest Nuamah',            'player'),
('Ghana', 454, 'Abdul Fatawu Issahaku',    'player'),
('Ghana', 455, 'Joseph Painstil',          'player'),
('Ghana', 456, 'Semenyo Antoine',          'player'),
('Ghana', 457, 'Daniel-Kofi Kyereh',       'player'),
('Ghana', 458, 'Kamaldeen Sulemana',       'player'),
('Ghana', 459, 'Elisha Owusu',             'player'),
('Ghana', 460, 'Richmond Boakye',          'player'),

-- =============================================
-- HONDURAS (461-480)
-- =============================================
('Honduras', 461, 'Escudo Honduras',       'badge'),
('Honduras', 462, 'Plantel Honduras',      'special'),
('Honduras', 463, 'Luis López',            'player'),
('Honduras', 464, 'Andy Najar',            'player'),
('Honduras', 465, 'Denil Maldonado',       'player'),
('Honduras', 466, 'Marcelo Santos',        'player'),
('Honduras', 467, 'Deybi Flores',          'player'),
('Honduras', 468, 'Bryan Acosta',          'player'),
('Honduras', 469, 'Alfredo Mejía',         'player'),
('Honduras', 470, 'Alberth Elis',          'player'),
('Honduras', 471, 'Romell Quioto',         'player'),
('Honduras', 472, 'Antony Lozano',         'player'),
('Honduras', 473, 'Rigoberto Rivas',       'player'),
('Honduras', 474, 'Luis Palma',            'player'),
('Honduras', 475, 'Jorge Álvarez',         'player'),
('Honduras', 476, 'Brayan Moya',           'player'),
('Honduras', 477, 'Diego Rodríguez',       'player'),
('Honduras', 478, 'Kevin López',           'player'),
('Honduras', 479, 'Harold Fonseca',        'player'),
('Honduras', 480, 'Iván López',            'player'),

-- =============================================
-- INDONESIA (481-500)
-- =============================================
('Indonesia', 481, 'Escudo Indonesia',       'badge'),
('Indonesia', 482, 'Plantel Indonesia',      'special'),
('Indonesia', 483, 'Nadeo Argawinata',       'player'),
('Indonesia', 484, 'Pratama Arhan',          'player'),
('Indonesia', 485, 'Justin Hubner',          'player'),
('Indonesia', 486, 'Jay Idzes',              'player'),
('Indonesia', 487, 'Rizky Ridho',            'player'),
('Indonesia', 488, 'Marc Klok',              'player'),
('Indonesia', 489, 'Ivar Jenner',            'player'),
('Indonesia', 490, 'Thom Haye',              'player'),
('Indonesia', 491, 'Rafael Struick',         'player'),
('Indonesia', 492, 'Marselino Ferdinan',     'player'),
('Indonesia', 493, 'Egy Maulana Vikri',      'player'),
('Indonesia', 494, 'Ragnar Oratmangoen',     'player'),
('Indonesia', 495, 'Kevin Diks',             'player'),
('Indonesia', 496, 'Sandy Walsh',            'player'),
('Indonesia', 497, 'Nathan Tjoe-A-On',       'player'),
('Indonesia', 498, 'Calvin Verdonk',         'player'),
('Indonesia', 499, 'Jordi Amat',             'player'),
('Indonesia', 500, 'Elkan Baggott',          'player'),

-- =============================================
-- INGLATERRA (501-520)
-- =============================================
('Inglaterra', 501, 'Escudo Inglaterra',      'badge'),
('Inglaterra', 502, 'Plantel Inglaterra',     'special'),
('Inglaterra', 503, 'Jordan Pickford',        'player'),
('Inglaterra', 504, 'Aaron Ramsdale',         'player'),
('Inglaterra', 505, 'Trent Alexander-Arnold', 'player'),
('Inglaterra', 506, 'Kieran Trippier',        'player'),
('Inglaterra', 507, 'John Stones',            'player'),
('Inglaterra', 508, 'Marc Guehi',             'player'),
('Inglaterra', 509, 'Luke Shaw',              'player'),
('Inglaterra', 510, 'Declan Rice',            'player'),
('Inglaterra', 511, 'Jude Bellingham',        'player'),
('Inglaterra', 512, 'Phil Foden',             'player'),
('Inglaterra', 513, 'Bukayo Saka',            'player'),
('Inglaterra', 514, 'Harry Kane',             'player'),
('Inglaterra', 515, 'Marcus Rashford',        'player'),
('Inglaterra', 516, 'Ollie Watkins',          'player'),
('Inglaterra', 517, 'Cole Palmer',            'player'),
('Inglaterra', 518, 'Anthony Gordon',         'player'),
('Inglaterra', 519, 'Kobbie Mainoo',          'player'),
('Inglaterra', 520, 'Levi Colwill',           'player'),

-- =============================================
-- IRAK (521-540)
-- =============================================
('Irak', 521, 'Escudo Irak',         'badge'),
('Irak', 522, 'Plantel Irak',        'special'),
('Irak', 523, 'Jalal Hassan',        'player'),
('Irak', 524, 'Ahmed Ibrahim',       'player'),
('Irak', 525, 'Ali Adnan',           'player'),
('Irak', 526, 'Amjad Attwan',        'player'),
('Irak', 527, 'Hussein Ali',         'player'),
('Irak', 528, 'Bashar Resan',        'player'),
('Irak', 529, 'Ayman Hussein',       'player'),
('Irak', 530, 'Mohannad Ali',        'player'),
('Irak', 531, 'Osama Rashid',        'player'),
('Irak', 532, 'Omar Abdullah',       'player'),
('Irak', 533, 'Mustafa Mohammed',    'player'),
('Irak', 534, 'Mahdi Kamil',         'player'),
('Irak', 535, 'Ali Faez',            'player'),
('Irak', 536, 'Saad Abdul Amir',     'player'),
('Irak', 537, 'Ahmed Salam',         'player'),
('Irak', 538, 'Ahmed Yadullah',      'player'),
('Irak', 539, 'Hammam Tahrour',      'player'),
('Irak', 540, 'Ali Al-Hamadi',       'player'),

-- =============================================
-- IRÁN (541-560)
-- =============================================
('Irán', 541, 'Escudo Irán',            'badge'),
('Irán', 542, 'Plantel Irán',           'special'),
('Irán', 543, 'Alireza Beiranvand',     'player'),
('Irán', 544, 'Mehdi Taremi',           'player'),
('Irán', 545, 'Sardar Azmoun',          'player'),
('Irán', 546, 'Ehsan Hajsafi',          'player'),
('Irán', 547, 'Shojae Khalilzadeh',     'player'),
('Irán', 548, 'Majid Hosseini',         'player'),
('Irán', 549, 'Saeid Ezatolahi',        'player'),
('Irán', 550, 'Milad Mohammadi',        'player'),
('Irán', 551, 'Ali Gholizadeh',         'player'),
('Irán', 552, 'Allahyar Sayyadmanesh',  'player'),
('Irán', 553, 'Roozbeh Cheshmi',        'player'),
('Irán', 554, 'Ahmad Nourollahi',       'player'),
('Irán', 555, 'Mehdi Shiri',            'player'),
('Irán', 556, 'Mahdi Torabi',           'player'),
('Irán', 557, 'Saman Ghoddos',          'player'),
('Irán', 558, 'Karim Ansarifard',       'player'),
('Irán', 559, 'Omid Ebrahimi',          'player'),
('Irán', 560, 'Saman Rezaei',           'player'),

-- =============================================
-- JAMAICA (561-580)
-- =============================================
('Jamaica', 561, 'Escudo Jamaica',          'badge'),
('Jamaica', 562, 'Plantel Jamaica',         'special'),
('Jamaica', 563, 'Andre Blake',             'player'),
('Jamaica', 564, 'Leon Bailey',             'player'),
('Jamaica', 565, 'Michail Antonio',         'player'),
('Jamaica', 566, 'Bobby Decordova-Reid',    'player'),
('Jamaica', 567, 'Demarai Gray',            'player'),
('Jamaica', 568, 'Kasey Palmer',            'player'),
('Jamaica', 569, 'Daniel Johnson',          'player'),
('Jamaica', 570, 'Javain Brown',            'player'),
('Jamaica', 571, 'Damion Lowe',             'player'),
('Jamaica', 572, 'Oniel Fisher',            'player'),
('Jamaica', 573, 'Liam Moore',              'player'),
('Jamaica', 574, 'Lamar Walker',            'player'),
('Jamaica', 575, 'Tyreece John-Jules',      'player'),
('Jamaica', 576, 'Junior Flemmings',        'player'),
('Jamaica', 577, 'Shamar Nicholson',        'player'),
('Jamaica', 578, 'Mipo Odubeko',            'player'),
('Jamaica', 579, 'Adrian Mariappa',         'player'),
('Jamaica', 580, 'Nicque Daley',            'player'),

-- =============================================
-- JAPÓN (581-600)
-- =============================================
('Japón', 581, 'Escudo Japón',          'badge'),
('Japón', 582, 'Plantel Japón',         'special'),
('Japón', 583, 'Shuichi Gonda',         'player'),
('Japón', 584, 'Takehiro Tomiyasu',     'player'),
('Japón', 585, 'Hiroki Ito',            'player'),
('Japón', 586, 'Shogo Taniguchi',       'player'),
('Japón', 587, 'Yuto Nagatomo',         'player'),
('Japón', 588, 'Wataru Endō',           'player'),
('Japón', 589, 'Daichi Kamada',         'player'),
('Japón', 590, 'Hidemasa Morita',       'player'),
('Japón', 591, 'Ao Tanaka',             'player'),
('Japón', 592, 'Reo Hatate',            'player'),
('Japón', 593, 'Kaoru Mitoma',          'player'),
('Japón', 594, 'Junya Ito',             'player'),
('Japón', 595, 'Takumi Minamino',       'player'),
('Japón', 596, 'Ritsu Doan',            'player'),
('Japón', 597, 'Ayase Ueda',            'player'),
('Japón', 598, 'Kyogo Furuhashi',       'player'),
('Japón', 599, 'Maya Yoshida',          'player'),
('Japón', 600, 'Mao Hosoya',            'player'),

-- =============================================
-- JORDANIA (601-620)
-- =============================================
('Jordania', 601, 'Escudo Jordania',         'badge'),
('Jordania', 602, 'Plantel Jordania',        'special'),
('Jordania', 603, 'Amer Shafi',              'player'),
('Jordania', 604, 'Musa Al-Taamari',         'player'),
('Jordania', 605, 'Yazan Al-Naimat',         'player'),
('Jordania', 606, 'Baha Faisal',             'player'),
('Jordania', 607, 'Abdallah Nasib',          'player'),
('Jordania', 608, 'Ahmad Burqan',            'player'),
('Jordania', 609, 'Monther Abu Amara',       'player'),
('Jordania', 610, 'Nour Al-Rawabdeh',        'player'),
('Jordania', 611, 'Ali Olwan',               'player'),
('Jordania', 612, 'Ibrahim Saied',           'player'),
('Jordania', 613, 'Mohammad Al-Dmeiri',      'player'),
('Jordania', 614, 'Ahmad Al-Sarori',         'player'),
('Jordania', 615, 'Yosef Al-Ahmad',          'player'),
('Jordania', 616, 'Zaid Al-Hamdan',          'player'),
('Jordania', 617, 'Amir Al-Ammari',          'player'),
('Jordania', 618, 'Salam Al-Aqrabawi',       'player'),
('Jordania', 619, 'Hamzah Al-Dardour',       'player'),
('Jordania', 620, 'Oday Dabbagh',            'player'),

-- =============================================
-- MARRUECOS (621-640)
-- =============================================
('Marruecos', 621, 'Escudo Marruecos',       'badge'),
('Marruecos', 622, 'Plantel Marruecos',      'special'),
('Marruecos', 623, 'Yassine Bounou "Bono"',  'player'),
('Marruecos', 624, 'Achraf Hakimi',          'player'),
('Marruecos', 625, 'Nayef Aguerd',           'player'),
('Marruecos', 626, 'Romain Saïss',           'player'),
('Marruecos', 627, 'Noussair Mazraoui',      'player'),
('Marruecos', 628, 'Sofyan Amrabat',         'player'),
('Marruecos', 629, 'Azzedine Ounahi',        'player'),
('Marruecos', 630, 'Bilal El Khannous',      'player'),
('Marruecos', 631, 'Youssef En-Nesyri',      'player'),
('Marruecos', 632, 'Hakim Ziyech',           'player'),
('Marruecos', 633, 'Sofiane Boufal',         'player'),
('Marruecos', 634, 'Zakaria Aboukhlal',      'player'),
('Marruecos', 635, 'Ilias Chair',            'player'),
('Marruecos', 636, 'Brahim Díaz',            'player'),
('Marruecos', 637, 'Yahia Attiyat Allah',    'player'),
('Marruecos', 638, 'Jawad El Yamiq',         'player'),
('Marruecos', 639, 'Hamza Igamane',          'player'),
('Marruecos', 640, 'Tarik Tissoudali',       'player'),

-- =============================================
-- MÉXICO (641-660)
-- =============================================
('México', 641, 'Escudo México',          'badge'),
('México', 642, 'Plantel México',         'special'),
('México', 643, 'Luis Malagón',           'player'),
('México', 644, 'Guillermo Ochoa',        'player'),
('México', 645, 'Jorge Sánchez',          'player'),
('México', 646, 'Jesús Gallardo',         'player'),
('México', 647, 'Johan Vásquez',          'player'),
('México', 648, 'César Montes',           'player'),
('México', 649, 'Edson Álvarez',          'player'),
('México', 650, 'Luis Romo',              'player'),
('México', 651, 'Roberto Alvarado',       'player'),
('México', 652, 'Orbelin Pineda',         'player'),
('México', 653, 'Hirving "Chucky" Lozano','player'),
('México', 654, 'Santiago Giménez',       'player'),
('México', 655, 'Henry Martín',           'player'),
('México', 656, 'Uriel Antuna',           'player'),
('México', 657, 'Julián Araujo',          'player'),
('México', 658, 'Alexis Vega',            'player'),
('México', 659, 'Emilio Lara',            'player'),
('México', 660, 'Tahir Jiménez',          'player'),

-- =============================================
-- NIGERIA (661-680)
-- =============================================
('Nigeria', 661, 'Escudo Nigeria',          'badge'),
('Nigeria', 662, 'Plantel Nigeria',         'special'),
('Nigeria', 663, 'Stanley Nwabali',         'player'),
('Nigeria', 664, 'Francis Uzoho',           'player'),
('Nigeria', 665, 'Ola Aina',                'player'),
('Nigeria', 666, 'Leon Balogun',            'player'),
('Nigeria', 667, 'William Troost-Ekong',    'player'),
('Nigeria', 668, 'Zaidu Sanusi',            'player'),
('Nigeria', 669, 'Wilfried Ndidi',          'player'),
('Nigeria', 670, 'Frank Onyeka',            'player'),
('Nigeria', 671, 'Joe Aribo',               'player'),
('Nigeria', 672, 'Alex Iwobi',              'player'),
('Nigeria', 673, 'Samuel Chukwueze',        'player'),
('Nigeria', 674, 'Ademola Lookman',         'player'),
('Nigeria', 675, 'Victor Osimhen',          'player'),
('Nigeria', 676, 'Taiwo Awoniyi',           'player'),
('Nigeria', 677, 'Terem Moffi',             'player'),
('Nigeria', 678, 'Calvin Bassey',           'player'),
('Nigeria', 679, 'Moses Simon',             'player'),
('Nigeria', 680, 'Kelechi Iheanacho',       'player'),

-- =============================================
-- NORUEGA (681-700)
-- =============================================
('Noruega', 681, 'Escudo Noruega',          'badge'),
('Noruega', 682, 'Plantel Noruega',         'special'),
('Noruega', 683, 'Ørjan Nyland',            'player'),
('Noruega', 684, 'Erling Haaland',          'player'),
('Noruega', 685, 'Martin Ødegaard',         'player'),
('Noruega', 686, 'Alexander Sørloth',       'player'),
('Noruega', 687, 'Sander Berge',            'player'),
('Noruega', 688, 'Stefan Strandberg',       'player'),
('Noruega', 689, 'Leo Ostigard',            'player'),
('Noruega', 690, 'Kristoffer Ajer',         'player'),
('Noruega', 691, 'Patrick Berg',            'player'),
('Noruega', 692, 'Kristian Thorstvedt',     'player'),
('Noruega', 693, 'Mohamed Elyounoussi',     'player'),
('Noruega', 694, 'Jens Petter Hauge',       'player'),
('Noruega', 695, 'Morten Thorsby',          'player'),
('Noruega', 696, 'Håkon Evjen',             'player'),
('Noruega', 697, 'Andreas Hoelgebaum',      'player'),
('Noruega', 698, 'Mathias Normann',         'player'),
('Noruega', 699, 'Joshua King',             'player'),
('Noruega', 700, 'Ola Solbakken',           'player'),

-- =============================================
-- NUEVA ZELANDA (701-720)
-- =============================================
('Nueva Zelanda', 701, 'Escudo Nueva Zelanda',  'badge'),
('Nueva Zelanda', 702, 'Plantel Nueva Zelanda', 'special'),
('Nueva Zelanda', 703, 'Oliver Sail',           'player'),
('Nueva Zelanda', 704, 'Chris Wood',            'player'),
('Nueva Zelanda', 705, 'Michael Boxall',        'player'),
('Nueva Zelanda', 706, 'Liberato Cacace',       'player'),
('Nueva Zelanda', 707, 'Ryan Thomas',           'player'),
('Nueva Zelanda', 708, 'Joe Bell',              'player'),
('Nueva Zelanda', 709, 'Myer Bevan',            'player'),
('Nueva Zelanda', 710, 'Clayton Lewis',         'player'),
('Nueva Zelanda', 711, 'Sarpreet Singh',        'player'),
('Nueva Zelanda', 712, 'Alex Greive',           'player'),
('Nueva Zelanda', 713, 'Callum McCowatt',       'player'),
('Nueva Zelanda', 714, 'Gianni Stensness',      'player'),
('Nueva Zelanda', 715, 'Marko Stamenic',        'player'),
('Nueva Zelanda', 716, 'Matt Garbett',          'player'),
('Nueva Zelanda', 717, 'Ben Old',               'player'),
('Nueva Zelanda', 718, 'Bill Tuilagi',          'player'),
('Nueva Zelanda', 719, 'Kosta Barbarouses',     'player'),
('Nueva Zelanda', 720, 'Winston Reid',          'player'),

-- =============================================
-- PAÍSES BAJOS (721-740)
-- =============================================
('Países Bajos', 721, 'Escudo Países Bajos',  'badge'),
('Países Bajos', 722, 'Plantel Países Bajos', 'special'),
('Países Bajos', 723, 'Bart Verbruggen',      'player'),
('Países Bajos', 724, 'Mark Flekken',         'player'),
('Países Bajos', 725, 'Virgil van Dijk',      'player'),
('Países Bajos', 726, 'Matthijs de Ligt',     'player'),
('Países Bajos', 727, 'Stefan de Vrij',       'player'),
('Países Bajos', 728, 'Nathan Aké',           'player'),
('Países Bajos', 729, 'Denzel Dumfries',      'player'),
('Países Bajos', 730, 'Georginio Wijnaldum',  'player'),
('Países Bajos', 731, 'Tijjani Reijnders',    'player'),
('Países Bajos', 732, 'Ryan Gravenberch',     'player'),
('Países Bajos', 733, 'Xavi Simons',          'player'),
('Países Bajos', 734, 'Cody Gakpo',           'player'),
('Países Bajos', 735, 'Donyell Malen',        'player'),
('Países Bajos', 736, 'Brian Brobbey',        'player'),
('Países Bajos', 737, 'Wout Weghorst',        'player'),
('Países Bajos', 738, 'Steven Bergwijn',      'player'),
('Países Bajos', 739, 'Jeremie Frimpong',     'player'),
('Países Bajos', 740, 'Lutsharel Geertruida', 'player'),

-- =============================================
-- PANAMÁ (741-760)
-- =============================================
('Panamá', 741, 'Escudo Panamá',          'badge'),
('Panamá', 742, 'Plantel Panamá',         'special'),
('Panamá', 743, 'Luis Mejía',             'player'),
('Panamá', 744, 'Harold Cummings',        'player'),
('Panamá', 745, 'Fidel Escobar',          'player'),
('Panamá', 746, 'Andrés Andrade',         'player'),
('Panamá', 747, 'Anibal Godoy',           'player'),
('Panamá', 748, 'Adalberto Carrasquilla', 'player'),
('Panamá', 749, 'Alberto Quintero',       'player'),
('Panamá', 750, 'Édgar Bárcenas',         'player'),
('Panamá', 751, 'Cecilio Waterman',       'player'),
('Panamá', 752, 'José Fajardo',           'player'),
('Panamá', 753, 'Rolando Blackburn',      'player'),
('Panamá', 754, 'Kevin Archibold',        'player'),
('Panamá', 755, 'Freddy Góndola',         'player'),
('Panamá', 756, 'Cristian Martínez',      'player'),
('Panamá', 757, 'Azmahar Ariano',         'player'),
('Panamá', 758, 'Michael Amir Murillo',   'player'),
('Panamá', 759, 'Tomás Córdoba',          'player'),
('Panamá', 760, 'Abdiel Ayarza',          'player'),

-- =============================================
-- PARAGUAY (761-780)
-- =============================================
('Paraguay', 761, 'Escudo Paraguay',       'badge'),
('Paraguay', 762, 'Plantel Paraguay',      'special'),
('Paraguay', 763, 'Antony Silva',          'player'),
('Paraguay', 764, 'Robert Rojas',          'player'),
('Paraguay', 765, 'Fabián Balbuena',       'player'),
('Paraguay', 766, 'Omar Alderete',         'player'),
('Paraguay', 767, 'Blas Riveros',          'player'),
('Paraguay', 768, 'Mathías Villasanti',    'player'),
('Paraguay', 769, 'Miguel Almirón',        'player'),
('Paraguay', 770, 'Ángel Cardozo',         'player'),
('Paraguay', 771, 'Marcelo Palau',         'player'),
('Paraguay', 772, 'Ramón Sosa',            'player'),
('Paraguay', 773, 'Julio Enciso',          'player'),
('Paraguay', 774, 'Antonio Sanabria',      'player'),
('Paraguay', 775, 'Alejandro Romero Gamarra "Kaku"', 'player'),
('Paraguay', 776, 'Óscar Romero',          'player'),
('Paraguay', 777, 'Santiago Arzamendia',   'player'),
('Paraguay', 778, 'Gustavo Velázquez',     'player'),
('Paraguay', 779, 'Hugo Quintana',         'player'),
('Paraguay', 780, 'Diego Gómez',           'player'),

-- =============================================
-- PERÚ (781-800)
-- =============================================
('Perú', 781, 'Escudo Perú',              'badge'),
('Perú', 782, 'Plantel Perú',             'special'),
('Perú', 783, 'Pedro Gallese',            'player'),
('Perú', 784, 'Luis Advíncula',           'player'),
('Perú', 785, 'Alexander Callens',        'player'),
('Perú', 786, 'Carlos Zambrano',          'player'),
('Perú', 787, 'Miguel Trauco',            'player'),
('Perú', 788, 'Renato Tapia',             'player'),
('Perú', 789, 'Wilder Cartagena',         'player'),
('Perú', 790, 'Sergio Peña',              'player'),
('Perú', 791, 'Yoshimar Yotún',           'player'),
('Perú', 792, 'Christian Cueva',          'player'),
('Perú', 793, 'André Carrillo',           'player'),
('Perú', 794, 'Edison Flores',            'player'),
('Perú', 795, 'Gianluca Lapadula',        'player'),
('Perú', 796, 'Paolo Guerrero',           'player'),
('Perú', 797, 'Bryan Reyna',              'player'),
('Perú', 798, 'Oliver Sonne',             'player'),
('Perú', 799, 'Joao Grimaldo',            'player'),
('Perú', 800, 'Marcos López',             'player'),

-- =============================================
-- PORTUGAL (801-820)
-- =============================================
('Portugal', 801, 'Escudo Portugal',       'badge'),
('Portugal', 802, 'Plantel Portugal',      'special'),
('Portugal', 803, 'Diogo Costa',           'player'),
('Portugal', 804, 'Rui Patrício',          'player'),
('Portugal', 805, 'João Cancelo',          'player'),
('Portugal', 806, 'Rúben Dias',            'player'),
('Portugal', 807, 'Pepe',                  'player'),
('Portugal', 808, 'Nuno Mendes',           'player'),
('Portugal', 809, 'Vitinha',               'player'),
('Portugal', 810, 'Rúben Neves',           'player'),
('Portugal', 811, 'Bruno Fernandes',       'player'),
('Portugal', 812, 'Bernardo Silva',        'player'),
('Portugal', 813, 'Cristiano Ronaldo',     'player'),
('Portugal', 814, 'Rafael Leão',           'player'),
('Portugal', 815, 'João Félix',            'player'),
('Portugal', 816, 'Gonçalo Ramos',         'player'),
('Portugal', 817, 'Pedro Neto',            'player'),
('Portugal', 818, 'Matheus Nunes',         'player'),
('Portugal', 819, 'Francisco Trincão',     'player'),
('Portugal', 820, 'Otávio',               'player'),

-- =============================================
-- QATAR (821-840)
-- =============================================
('Qatar', 821, 'Escudo Qatar',            'badge'),
('Qatar', 822, 'Plantel Qatar',           'special'),
('Qatar', 823, 'Meshaal Barsham',         'player'),
('Qatar', 824, 'Almoez Ali',              'player'),
('Qatar', 825, 'Akram Afif',              'player'),
('Qatar', 826, 'Hassan Al-Haydos',        'player'),
('Qatar', 827, 'Abdulaziz Hatem',         'player'),
('Qatar', 828, 'Mohammed Muntari',        'player'),
('Qatar', 829, 'Abdelkarim Hassan',       'player'),
('Qatar', 830, 'Bassam Al-Rawi',          'player'),
('Qatar', 831, 'Pedro Miguel',            'player'),
('Qatar', 832, 'Assim Omer Madibo',       'player'),
('Qatar', 833, 'Karim Boudiaf',           'player'),
('Qatar', 834, 'Ahmed Alaaeldin',         'player'),
('Qatar', 835, 'Salem Al-Hajri',          'player'),
('Qatar', 836, 'Yusuf Abdurisag',         'player'),
('Qatar', 837, 'Ismail Mohammad',         'player'),
('Qatar', 838, 'Ahmad Al-Rawi',           'player'),
('Qatar', 839, 'Homam Ahmed',             'player'),
('Qatar', 840, 'Ahmed Khalid Siddiqui',   'player'),

-- =============================================
-- SENEGAL (841-860)
-- =============================================
('Senegal', 841, 'Escudo Senegal',         'badge'),
('Senegal', 842, 'Plantel Senegal',        'special'),
('Senegal', 843, 'Édouard Mendy',          'player'),
('Senegal', 844, 'Seny Dieng',             'player'),
('Senegal', 845, 'Kalidou Koulibaly',      'player'),
('Senegal', 846, 'Abdou Diallo',           'player'),
('Senegal', 847, 'Moussa Niakhaté',        'player'),
('Senegal', 848, 'Formose Mendy',          'player'),
('Senegal', 849, 'Idrissa Gueye',          'player'),
('Senegal', 850, 'Pape Matar Sarr',        'player'),
('Senegal', 851, 'Lamine Camara',          'player'),
('Senegal', 852, 'Sadio Mané',             'player'),
('Senegal', 853, 'Ismaïla Sarr',           'player'),
('Senegal', 854, 'Iliman Ndiaye',          'player'),
('Senegal', 855, 'Nicolas Jackson',        'player'),
('Senegal', 856, 'Boulaye Dia',            'player'),
('Senegal', 857, 'Habib Diallo',           'player'),
('Senegal', 858, 'Krepin Diatta',          'player'),
('Senegal', 859, 'Famara Diédhiou',        'player'),
('Senegal', 860, 'Nampalys Mendy',         'player'),

-- =============================================
-- SERBIA (861-880)
-- =============================================
('Serbia', 861, 'Escudo Serbia',              'badge'),
('Serbia', 862, 'Plantel Serbia',             'special'),
('Serbia', 863, 'Predrag Rajković',           'player'),
('Serbia', 864, 'Nikola Milenković',          'player'),
('Serbia', 865, 'Strahinja Pavlović',         'player'),
('Serbia', 866, 'Srđan Babić',               'player'),
('Serbia', 867, 'Filip Kostić',               'player'),
('Serbia', 868, 'Sergej Milinković-Savić',    'player'),
('Serbia', 869, 'Nemanja Gudelj',             'player'),
('Serbia', 870, 'Saša Lukić',                 'player'),
('Serbia', 871, 'Ivan Ilić',                  'player'),
('Serbia', 872, 'Dušan Tadić',                'player'),
('Serbia', 873, 'Nikola Vlašić',              'player'),
('Serbia', 874, 'Aleksandar Mitrović',        'player'),
('Serbia', 875, 'Dušan Vlahović',             'player'),
('Serbia', 876, 'Luka Jović',                 'player'),
('Serbia', 877, 'Andrija Živković',           'player'),
('Serbia', 878, 'Marko Lazović',              'player'),
('Serbia', 879, 'Veljko Birmančević',         'player'),
('Serbia', 880, 'Uros Racic',                 'player'),

-- =============================================
-- SUDÁFRICA (881-900)
-- =============================================
('Sudáfrica', 881, 'Escudo Sudáfrica',      'badge'),
('Sudáfrica', 882, 'Plantel Sudáfrica',     'special'),
('Sudáfrica', 883, 'Ronwen Williams',       'player'),
('Sudáfrica', 884, 'Veli Mothwa',           'player'),
('Sudáfrica', 885, 'Reeve Frosler',         'player'),
('Sudáfrica', 886, 'Siyanda Xulu',          'player'),
('Sudáfrica', 887, 'Rushine De Reuck',      'player'),
('Sudáfrica', 888, 'Terrence Mashego',      'player'),
('Sudáfrica', 889, 'Teboho Mokoena',        'player'),
('Sudáfrica', 890, 'Bongani Zungu',         'player'),
('Sudáfrica', 891, 'Sipho Mbule',           'player'),
('Sudáfrica', 892, 'Jayden Adams',          'player'),
('Sudáfrica', 893, 'Percy Tau',             'player'),
('Sudáfrica', 894, 'Themba Zwane',          'player'),
('Sudáfrica', 895, 'Keagan Dolly',          'player'),
('Sudáfrica', 896, 'Lyle Foster',           'player'),
('Sudáfrica', 897, 'Cassius Mailula',       'player'),
('Sudáfrica', 898, 'Sifiso Hlanti',         'player'),
('Sudáfrica', 899, 'Evidence Makgopa',      'player'),
('Sudáfrica', 900, 'Bradley Grobler',       'player'),

-- =============================================
-- SUIZA (901-920)
-- =============================================
('Suiza', 901, 'Escudo Suiza',           'badge'),
('Suiza', 902, 'Plantel Suiza',          'special'),
('Suiza', 903, 'Yann Sommer',            'player'),
('Suiza', 904, 'Gregor Kobel',           'player'),
('Suiza', 905, 'Silvan Widmer',          'player'),
('Suiza', 906, 'Manuel Akanji',          'player'),
('Suiza', 907, 'Fabian Schär',           'player'),
('Suiza', 908, 'Nico Elvedi',            'player'),
('Suiza', 909, 'Ricardo Rodriguez',      'player'),
('Suiza', 910, 'Granit Xhaka',           'player'),
('Suiza', 911, 'Remo Freuler',           'player'),
('Suiza', 912, 'Michel Aebischer',       'player'),
('Suiza', 913, 'Ardon Jashari',          'player'),
('Suiza', 914, 'Dan Ndoye',              'player'),
('Suiza', 915, 'Ruben Vargas',           'player'),
('Suiza', 916, 'Breel Embolo',           'player'),
('Suiza', 917, 'Zeki Amdouni',           'player'),
('Suiza', 918, 'Xherdan Shaqiri',        'player'),
('Suiza', 919, 'Kwadwo Duah',            'player'),
('Suiza', 920, 'Vincent Sierro',         'player'),

-- =============================================
-- TURQUÍA (921-940)
-- =============================================
('Turquía', 921, 'Escudo Turquía',          'badge'),
('Turquía', 922, 'Plantel Turquía',         'special'),
('Turquía', 923, 'Altay Bayındır',          'player'),
('Turquía', 924, 'Mert Günok',              'player'),
('Turquía', 925, 'Zeki Çelik',              'player'),
('Turquía', 926, 'Merih Demiral',           'player'),
('Turquía', 927, 'Kaan Ayhan',              'player'),
('Turquía', 928, 'Ferdi Kadıoğlu',          'player'),
('Turquía', 929, 'Hakan Çalhanoğlu',        'player'),
('Turquía', 930, 'Salih Özcan',             'player'),
('Turquía', 931, 'Abdülkerim Bardakcı',     'player'),
('Turquía', 932, 'Arda Güler',              'player'),
('Turquía', 933, 'Kerem Aktürkoğlu',        'player'),
('Turquía', 934, 'Barış Alper Yılmaz',      'player'),
('Turquía', 935, 'Yusuf Yazıcı',            'player'),
('Turquía', 936, 'Cengiz Ünder',            'player'),
('Turquía', 937, 'Cenk Tosun',              'player'),
('Turquía', 938, 'Ozan Kabak',              'player'),
('Turquía', 939, 'Samet Akaydın',           'player'),
('Turquía', 940, 'Baran Uzel',              'player'),

-- =============================================
-- UCRANIA (941-960)
-- =============================================
('Ucrania', 941, 'Escudo Ucrania',          'badge'),
('Ucrania', 942, 'Plantel Ucrania',         'special'),
('Ucrania', 943, 'Andriy Lunin',            'player'),
('Ucrania', 944, 'Georgiy Bushchan',        'player'),
('Ucrania', 945, 'Oleksandr Zinchenko',     'player'),
('Ucrania', 946, 'Illia Zabarnyi',          'player'),
('Ucrania', 947, 'Mykola Matvienko',        'player'),
('Ucrania', 948, 'Taras Stepanenko',        'player'),
('Ucrania', 949, 'Ruslan Malinovskyi',      'player'),
('Ucrania', 950, 'Mykola Shaparenko',       'player'),
('Ucrania', 951, 'Viktor Tsygankov',        'player'),
('Ucrania', 952, 'Mykhailo Mudryk',         'player'),
('Ucrania', 953, 'Oleksandr Zubkov',        'player'),
('Ucrania', 954, 'Artem Dovbyk',            'player'),
('Ucrania', 955, 'Roman Yaremchuk',         'player'),
('Ucrania', 956, 'Nazariy Rusyn',           'player'),
('Ucrania', 957, 'Valentyn Kastsirin',      'player'),
('Ucrania', 958, 'Yukhym Konoplya',         'player'),
('Ucrania', 959, 'Vitaliy Mykolenko',       'player'),
('Ucrania', 960, 'Bohdan Mykhaylichenko',   'player'),

-- =============================================
-- URUGUAY (961-980)
-- =============================================
('Uruguay', 961, 'Escudo Uruguay',          'badge'),
('Uruguay', 962, 'Plantel Uruguay',         'special'),
('Uruguay', 963, 'Sergio Rochet',           'player'),
('Uruguay', 964, 'Fernando Muslera',        'player'),
('Uruguay', 965, 'Ronald Araújo',           'player'),
('Uruguay', 966, 'José María Giménez',      'player'),
('Uruguay', 967, 'Mathías Olivera',         'player'),
('Uruguay', 968, 'Nahitan Nández',          'player'),
('Uruguay', 969, 'Lucas Torreira',          'player'),
('Uruguay', 970, 'Rodrigo Bentancur',       'player'),
('Uruguay', 971, 'Federico Valverde',       'player'),
('Uruguay', 972, 'Luis Suárez',             'player'),
('Uruguay', 973, 'Edinson Cavani',          'player'),
('Uruguay', 974, 'Darwin Núñez',            'player'),
('Uruguay', 975, 'Facundo Torres',          'player'),
('Uruguay', 976, 'Maximiliano Araújo',      'player'),
('Uruguay', 977, 'Matías Vecino',           'player'),
('Uruguay', 978, 'Brian Rodríguez',         'player'),
('Uruguay', 979, 'Sebastián Coates',        'player'),
('Uruguay', 980, 'Maxi Gómez',              'player');
